// Building the output files — in the browser, from the original file.
//
// Only the confirmed terminology fragments are changed; nothing is
// regenerated by AI and everything else (structure, numbers, names, tables,
// formatting) stays byte-for-byte as it was:
//   DOCX -> the original package with the fragment rewritten inside its own
//           <w:t> runs, so run formatting (bold, font, size) is kept.
//   PDF  -> the original PDF; on pages with a text layer the rest of the line
//           from the fragment on is covered and redrawn with the fix. Fixes
//           on scanned pages can't be written into the picture and go into
//           the corrected text version instead (and the report says so).
//   Image / scan -> a DOCX with the recognised, corrected text.
// Plus the inspection report as a DOCX table.

import { parseDocxXml, W_NS } from './extract.js'

const XML_NS = 'http://www.w3.org/XML/1998/namespace'
const DOCX_MIME = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'

/** Text with fixes applied (fixes: { start, end, suggestion }, non-overlapping). */
export function applyToText(text, fixes) {
  let out = text
  for (const fix of [...fixes].sort((a, b) => b.start - a.start)) {
    out = out.slice(0, fix.start) + fix.suggestion + out.slice(fix.end)
  }
  return out
}

function baseName(fileName) {
  return fileName.replace(/\.[^.]+$/, '') || 'document'
}

// ---- DOCX: corrections in place ----------------------------------------------

/**
 * Only the part that actually differs: «аварийно спасательной» ->
 * «аварийно-спасательной» touches just the space, so a bold «аварийно» in
 * its own run keeps its formatting.
 */
function minimalEdit(original, replacement) {
  let from = 0
  while (from < original.length && from < replacement.length && original[from] === replacement[from]) from++
  let trimEnd = 0
  while (
    trimEnd < original.length - from &&
    trimEnd < replacement.length - from &&
    original[original.length - 1 - trimEnd] === replacement[replacement.length - 1 - trimEnd]
  ) {
    trimEnd++
  }
  return { from, trimEnd, text: replacement.slice(from, replacement.length - trimEnd) }
}

/** Rewrites page-text range [start, end) inside the paragraph's <w:t> runs. */
function replaceInRuns(runs, start, end, replacement) {
  if (start === end) {
    // Pure insertion (a missing hyphen): into the run the position is in.
    const run = runs.find((r) => start >= r.start && start <= r.end)
    if (!run) return false
    const value = run.node.textContent
    run.node.textContent = value.slice(0, start - run.start) + replacement + value.slice(start - run.start)
    run.node.setAttributeNS(XML_NS, 'xml:space', 'preserve')
    return true
  }
  const touched = runs.filter((r) => r.start < end && start < r.end)
  if (!touched.length) return false
  // The range must consist of run text only (no tab / line break inside).
  const covered = touched.reduce((n, r) => n + Math.min(end, r.end) - Math.max(start, r.start), 0)
  if (covered !== end - start) return false
  touched.forEach((r, i) => {
    const value = r.node.textContent
    const a = Math.max(start, r.start) - r.start
    const b = Math.min(end, r.end) - r.start
    r.node.textContent = value.slice(0, a) + (i === 0 ? replacement : '') + value.slice(b)
    r.node.setAttributeNS(XML_NS, 'xml:space', 'preserve')
  })
  return true
}

async function correctedDocx(doc, fixes, status) {
  // Re-parse the original XML: identical offsets, untouched DOM.
  const { dom, paragraphs } = parseDocxXml(doc.docx.xml)
  const byParagraph = new Map()
  for (const fix of fixes) {
    const para = paragraphs.find(
      (p) => p.page === fix.page && fix.start >= p.offset && fix.end <= p.offset + p.text.length,
    )
    if (!para) {
      status.set(fix.id, 'failed')
      continue
    }
    if (!byParagraph.has(para)) byParagraph.set(para, [])
    byParagraph.get(para).push(fix)
  }
  for (const [para, list] of byParagraph) {
    // Right to left, so earlier offsets stay valid.
    for (const fix of list.sort((a, b) => b.start - a.start)) {
      const edit = minimalEdit(fix.text, fix.suggestion)
      const start = fix.start - para.offset + edit.from
      const end = fix.end - para.offset - edit.trimEnd
      const ok = replaceInRuns(para.runs, start, end, edit.text)
      status.set(fix.id, ok ? 'applied' : 'failed')
    }
  }
  const xml = new XMLSerializer().serializeToString(dom)
  doc.docx.zip.file('word/document.xml', xml)
  const blob = await doc.docx.zip.generateAsync({ type: 'blob', mimeType: DOCX_MIME, compression: 'DEFLATE' })
  doc.docx.zip.file('word/document.xml', doc.docx.xml) // keep the original for a rebuild
  return blob
}

// ---- PDF: overlay on text-layer pages ----------------------------------------

async function correctedPdf(doc, fixes, status) {
  const [{ PDFDocument, rgb }, { default: fontkit }] = await Promise.all([import('pdf-lib'), import('@pdf-lib/fontkit')])
  const pdfDoc = await PDFDocument.load(doc.bytes, { ignoreEncryption: true })
  pdfDoc.registerFontkit(fontkit)
  const fontBytes = await fetch(`${import.meta.env.BASE_URL}fonts/DejaVuSans.ttf`).then((r) => r.arrayBuffer())
  // Full embed: subsetting in fontkit occasionally drops Cyrillic glyphs.
  const font = await pdfDoc.embedFont(fontBytes, { subset: false })

  for (const page of doc.pages) {
    const pageFixes = fixes.filter((f) => f.page === page.number)
    if (!pageFixes.length) continue
    if (page.source !== 'text') {
      pageFixes.forEach((f) => status.set(f.id, 'text_only'))
      continue
    }
    const pdfPage = pdfDoc.getPage(page.number - 1)

    // Group fixes by the text line they sit on.
    const byLine = new Map()
    for (const fix of pageFixes) {
      const spans = page.spans.filter((s) => s.start < fix.end && fix.start < s.end)
      const line = spans[0]?.line
      if (!spans.length || spans.some((s) => s.line !== line || s.rotated)) {
        status.set(fix.id, 'text_only') // crosses a line break / rotated text
        continue
      }
      if (!byLine.has(line)) byLine.set(line, [])
      byLine.get(line).push(fix)
    }

    for (const [line, lineFixes] of byLine) {
      const lineSpans = page.spans.filter((s) => s.line === line)
      const lineEnd = lineSpans.at(-1).end
      lineFixes.sort((a, b) => a.start - b.start)
      const first = lineFixes[0]
      // Redraw from the start of the text item holding the first fix: its x
      // is exact, while a position inside an item is only proportional and
      // would leave slivers of the old glyphs visible.
      const anchor = lineSpans.find((s) => first.start >= s.start && first.start < s.end) ?? lineSpans[0]
      const x0 = anchor.x
      const last = lineSpans.at(-1)
      const xEnd = last.x + last.width
      const size = anchor.size
      const y = anchor.y

      const tail = page.text.slice(anchor.start, lineEnd)
      const relative = lineFixes.map((f) => ({ ...f, start: f.start - anchor.start, end: f.end - anchor.start }))
      const newText = applyToText(tail, relative).replace(/\s+/g, ' ')

      // Cover the old rest of the line, draw the corrected rest of the line.
      const pageWidth = pdfPage.getWidth()
      const available = Math.max(xEnd - x0, Math.min(pageWidth - x0 - 20, xEnd - x0 + size * 2))
      let drawSize = size
      const width = font.widthOfTextAtSize(newText, size)
      if (width > available) drawSize = (size * available) / width
      pdfPage.drawRectangle({
        x: x0 - 0.5,
        y: y - size * 0.3,
        width: Math.max(xEnd - x0, font.widthOfTextAtSize(newText, drawSize)) + 1,
        height: size * 1.25,
        color: rgb(1, 1, 1),
      })
      pdfPage.drawText(newText, { x: x0, y, size: drawSize, font, color: rgb(0, 0, 0) })
      lineFixes.forEach((f) => status.set(f.id, 'applied'))
    }
  }
  const bytes = await pdfDoc.save()
  return new Blob([bytes], { type: 'application/pdf' })
}

// ---- Minimal DOCX builder (corrected text, report) ---------------------------

function esc(text) {
  return String(text)
    // oxlint-disable-next-line no-control-regex -- strips characters XML forbids
    .replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g, '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

const RUN_FONT = '<w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman" w:cs="Times New Roman"/>'

function run(text, { bold = false, size = 24, color } = {}) {
  const props = `${RUN_FONT}${bold ? '<w:b/>' : ''}${color ? `<w:color w:val="${color}"/>` : ''}<w:sz w:val="${size}"/>`
  const parts = String(text).split('\t')
  return parts
    .map((part, i) => `${i ? `<w:r><w:rPr>${props}</w:rPr><w:tab/></w:r>` : ''}<w:r><w:rPr>${props}</w:rPr><w:t xml:space="preserve">${esc(part)}</w:t></w:r>`)
    .join('')
}

function para(text, opts = {}) {
  const spacing = `<w:spacing w:after="${opts.after ?? 120}"/>`
  const align = opts.center ? '<w:jc w:val="center"/>' : ''
  return `<w:p><w:pPr>${spacing}${align}</w:pPr>${text === '' ? '' : run(text, opts)}</w:p>`
}

function table(rows, widths) {
  const border = (side) => `<w:${side} w:val="single" w:sz="4" w:space="0" w:color="808080"/>`
  const borders = `<w:tblBorders>${['top', 'left', 'bottom', 'right', 'insideH', 'insideV'].map(border).join('')}</w:tblBorders>`
  const grid = `<w:tblGrid>${widths.map((w) => `<w:gridCol w:w="${w}"/>`).join('')}</w:tblGrid>`
  const body = rows
    .map(
      (cells, r) =>
        `<w:tr>${cells
          .map(
            (cell, c) =>
              `<w:tc><w:tcPr><w:tcW w:w="${widths[c]}" w:type="dxa"/>${r === 0 ? '<w:shd w:val="clear" w:color="auto" w:fill="E7EEF7"/>' : ''}</w:tcPr><w:p><w:pPr><w:spacing w:after="0"/></w:pPr>${run(cell, { bold: r === 0, size: 20 })}</w:p></w:tc>`,
          )
          .join('')}</w:tr>`,
    )
    .join('')
  return `<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/>${borders}</w:tblPr>${grid}${body}</w:tbl>`
}

async function buildDocx(bodyXml) {
  const { default: JSZip } = await import('jszip')
  const zip = new JSZip()
  zip.file(
    '[Content_Types].xml',
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>',
  )
  zip.file(
    '_rels/.rels',
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>',
  )
  zip.file(
    'word/document.xml',
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="${W_NS}"><w:body>${bodyXml}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="850" w:bottom="1134" w:left="1418" w:header="708" w:footer="708" w:gutter="0"/></w:sectPr></w:body></w:document>`,
  )
  return zip.generateAsync({ type: 'blob', mimeType: DOCX_MIME, compression: 'DEFLATE' })
}

/** The recognised / extracted text with fixes applied, page by page. */
async function correctedTextDocx(doc, fixes, labels) {
  const parts = []
  for (const page of doc.pages) {
    if (!page.text.trim()) continue
    if (doc.pages.length > 1) parts.push(para(labels.pageHeading(page.number), { bold: true, color: '555555', after: 200 }))
    const text = applyToText(page.text, fixes.filter((f) => f.page === page.number))
    text.split('\n').forEach((line) => parts.push(para(line)))
  }
  return buildDocx(parts.join(''))
}

/**
 * Corrected files for the inspection.
 * @returns {Promise<{ files: Array<{ key: string, fileName: string, blob: Blob }>, status: Map<string, 'applied'|'text_only'|'failed'> }>}
 */
export async function buildCorrectedFiles(inspection, fixes, labels) {
  const { doc, fileName } = inspection
  const name = baseName(fileName)
  const status = new Map()
  const files = []
  if (doc.kind === 'docx') {
    files.push({ key: 'docx', fileName: `${name}_исправлено.docx`, blob: await correctedDocx(doc, fixes, status) })
  } else if (doc.kind === 'pdf') {
    let pdfBlob = null
    try {
      pdfBlob = await correctedPdf(doc, fixes, status)
    } catch (error) {
      console.error('Corrected PDF could not be built:', error)
      fixes.forEach((f) => status.set(f.id, 'text_only'))
    }
    if (pdfBlob) files.push({ key: 'pdf', fileName: `${name}_исправлено.pdf`, blob: pdfBlob })
    files.push({ key: 'text', fileName: `${name}_исправленный_текст.docx`, blob: await correctedTextDocx(doc, fixes, labels) })
  } else {
    fixes.forEach((f) => status.set(f.id, 'applied'))
    files.push({ key: 'text', fileName: `${name}_исправленный_текст.docx`, blob: await correctedTextDocx(doc, fixes, labels) })
  }
  return { files, status }
}

/**
 * The inspection report.
 * @param {{ title: string, meta: string[], columns: string[], rows: string[][] }} report
 */
export async function buildReportDocx(report) {
  const body = [
    para(report.title, { bold: true, size: 30, center: true, after: 240 }),
    ...report.meta.map((line) => para(line, { after: 60 })),
    para(''),
    table([report.columns, ...report.rows], [400, 700, 1500, 1500, 1300, 1200, 1700, 1300]),
  ]
  return buildDocx(body.join(''))
}

export function downloadBlob(blob, fileName) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = fileName
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 10_000)
}
