-- =============================================================
-- Batch add: firefighting / rescue / civil-defense terminology (154 terms).
-- Source: term list supplied directly by the site owner (kk/ru/en).
-- category values map to CATEGORIES keys in src/i18n/translations.js;
-- assigned by best judgement where the source list didn't specify one.
--
-- HOW TO RUN:
--   Open your Supabase project -> SQL Editor -> paste this file -> Run.
--   (This project only ships the anon key to the client, so this
--   migration cannot be applied automatically.)
-- =============================================================

insert into public.terms (kk, ru, en, category)
values
  ('периметр', 'периметр', 'perimeter', 'coordination'),
  ('пирогенді', 'пирогенный', 'pyrogenic', 'fire_safety'),
  ('пиролиз', 'пиролиз', 'pyrolysis', 'fire_safety'),
  ('пироман', 'пироман', 'pyromaniac, arsonist', 'fire_safety'),
  ('пирометр (өлшеуіш)', 'пирометр', 'pyrometer', 'fire_safety'),
  ('пирофор', 'пирофор', 'pyrophorus', 'fire_safety'),
  ('платформасы (тұғырнамасы) бар автокөтергіш', 'автоподъёмник с платформой', 'Elevating platform truck', 'rescue_ops'),
  ('пневматикалық қысымтығын клапан', 'пневматический клапан', 'pneumatic valve', 'rescue_ops'),
  ('пневматикалық қашау', 'пневматическое зубило', 'air chisel', 'rescue_ops'),
  ('пневматикалық шығыр', 'пневматическая лебёдка', 'pneumatic winch', 'rescue_ops'),
  ('үлбірлі қабықша', 'пленочное покрытие', '', 'industrial_safety'),
  ('диспетчер', 'диспетчер', 'dispatcher', 'coordination'),
  ('аға диспетчер', 'старший диспетчер', 'Senior Dispatcher', 'coordination'),
  ('диспетчерлік бақылау', 'диспетчерский контроль', 'Dispatch Control / Dispatcher Control', 'coordination'),
  ('понтон көпір', 'понтонный мост', 'boat bridge, float bridge, floating bridge', 'evacuation'),
  ('протеинді әмбебап көбік', 'универсальная протеиновая пена', 'protein all-purpose foam', 'fire_safety'),
  ('протеинді көбік', 'протеиновая пена', 'Protein foam', 'fire_safety'),
  ('протеинді көбіктендіргіш', 'протеиновый пенообразователь', 'Protein foam concentrate', 'fire_safety'),
  ('психологиялық ахуал', 'психологический климат', 'psychological climate', 'disaster_medicine'),
  ('моральдық-психологиялық ахуал', 'морально-психологическое состояние', 'moral and psychological state', 'disaster_medicine'),
  ('психологиялық тұзақ', 'психологическая ловушка', 'Psychological trap', 'disaster_medicine'),
  ('піспекті клапан', 'поршневой клапан', 'piston valve', 'industrial_safety'),
  ('радиациялық қауіп', 'радиационная опасность', 'Radiation warning', 'industrial_safety'),
  ('радиациялық қауіпсіздік', 'радиационная безопасность', 'radiological safety', 'industrial_safety'),
  ('радиациялық қауіпсіздік бойынша нормативті құжаттар', 'нормативные документы по радиационной безопасности', 'Radiation safety regulations', 'industrial_safety'),
  ('радиоактивті йодтың шоғырлануы', 'концентрация радиоактивного йода', 'Radio iodine concentration', 'industrial_safety'),
  ('радиобайланыс жүйесімен тыныс алу аппараты', 'дыхательный аппарат с системой радиосвязи', 'communication set breathing apparatus', 'rescue_ops'),
  ('радийбелсенділіктің шығарындылары', 'выброс радиоактивности', 'radiological release, release of radiation', 'industrial_safety'),
  ('автоматты трансляция (хабар тарату)', 'автоматическая трансляция', 'Automatic broadcast', 'alerting_comms'),
  ('радийизотопты өрт хабарлағышы', 'радиоизотопный пожарный оповещатель', 'radiation detector', 'fire_safety'),
  ('радиосәулелену қуаты (өртті қоздыруға арналған)', 'мощность радиоизлучения (для инициирования пожара)', 'radio-frequency power', 'fire_safety'),
  ('резервтік аппарат', 'резервный аппарат', 'reserve apparatus', 'fire_safety'),
  ('резервтік өрт сөндірушілер командасы', 'резервная пожарная команда', 'reserve fire team', 'fire_safety'),
  ('резервтік автомобиль', 'резервный автомобиль', 'Reserve engine', 'fire_safety'),
  ('резервуарлық парк', 'резервуарный парк', 'tank farm', 'industrial_safety'),
  ('ресурстар санаты', 'категория ресурсов', 'resource category', 'coordination'),
  ('рұқсат етілген концентрация', 'допустимая концентрация', 'allowable concentration', 'industrial_safety'),
  ('сақтандырылған; сақтандырылушы', 'застрахованный', 'assured, insurant, secure', 'civil_defense'),
  ('салқындатқыш сұйықтық', 'охлаждающая жидкость', 'coolant', 'industrial_safety'),
  ('салқындау, суу, суыту, суыну', 'охлаждение', 'cooling, refrigeration', 'industrial_safety'),
  ('санитарлық-алдын алу іс-шаралары', 'санитарно-профилактические мероприятия', 'sanitary arrangements', 'disaster_medicine'),
  ('саптама таңдау', 'выбор насадки', 'nozzle selection', 'fire_safety'),
  ('автосаты', 'автолестница', 'ladder truck', 'fire_safety'),
  ('автомеханикалық саты', 'автомеханическая лестница', 'aerial ladder, turntable ladder', 'fire_safety'),
  ('сәулелену, сәуле шығару, сәулелендіру', 'излучение', 'radiation emission, ray', 'industrial_safety'),
  ('сәулелену қуаттылығы', 'мощность излучения', 'emissive power', 'industrial_safety'),
  ('жылжымалы өрт сөндіру сатысы', 'выдвижная пожарная лестница', 'extension ladder', 'fire_safety'),
  ('су тасқыны, топан су', 'наводнение', 'flood, flooding, flood situation, flood incident, inundation', 'emergencies'),
  ('мұздық тасқыны', 'наводнение ледниковое', 'glacial flood, glacial lake outburst flood (GLOF) — наводнение, вызванное прорывом ледникового озера', 'emergencies'),
  ('синергетикалық апат', 'синергетическое бедствие', 'synergistic disaster', 'emergencies'),
  ('сорғы агрегат', 'насосный агрегат', '', 'fire_safety'),
  ('айналмалы сусорғы', 'насос водокольцевой', '', 'fire_safety'),
  ('көбікпен өрт сөндіру сорабы', 'насосная пенопожаротушение', 'foam pumping station', 'fire_safety'),
  ('сортаңдауы (жердің)', 'засоление (почвы)', 'salinization', 'industrial_safety'),
  ('судың тұздануы', 'засоление воды', 'water salinization / salinization of water', 'industrial_safety'),
  ('топырақтың сортаңдануы', 'засоление почвы', 'soil salinization', 'industrial_safety'),
  ('сөнбеген жанартау', 'действующий вулкан', 'erupting volcano', 'emergencies'),
  ('жанартау атқылауы', 'вулканическое извержение', 'volcanic eruption', 'emergencies'),
  ('жанартаулық жер сілкінісі', 'вулканическое землетрясение', 'volcanic earthquake', 'emergencies'),
  ('сөнген жанартау', 'потухший вулкан', 'extinct volcano', 'emergencies'),
  ('көмір қышқылды өрт сөндіргіш', 'огнетушитель углекислотный', 'carbon dioxide fire extinguisher (CO2 fire extinguisher)', 'fire_safety'),
  ('ұнтақты өрт сөндіргіш', 'огнетушитель порошковый', 'dry powder fire extinguisher', 'fire_safety'),
  ('сөндіру уақыты', 'время тушения', 'extinguishing time', 'fire_safety'),
  ('сөндіруге бой бермейтін', 'не поддающиеся тушению', 'not amenable to extinguishment / difficult to extinguish', 'fire_safety'),
  ('аспалы өрт сөндіру жүйесі', 'ранцевая система пожаротушения', 'backpack fire suppression system', 'fire_safety'),
  ('газбен өрт сөндірудің автоматты жүйесі', 'автоматическая система газового пожаротушения', 'automatic gaseous fire extinguishing system', 'fire_safety'),
  ('дренчерлік өрт сөндірудің автоматты жүйесі', 'автоматическая система дренчерного пожаротушения', 'automatic deluge fire extinguishing system', 'fire_safety'),
  ('көбік-ұнтақпен өрт сөндіру автомобилі', 'автомобиль пожарный пенно-порошкового тушения', 'foam and dry powder fire-fighting vehicle', 'fire_safety'),
  ('көбікпен өрт сөндірудің автоматты жүйесі', 'автоматическая система пенного пожаротушения', 'automatic foam fire extinguishing system', 'fire_safety'),
  ('көмірқышқылмен өрт сөндіру қондырғысы бар өрт сөндіру автомобилі', 'автомобиль пожарный с углекислотной установкой пожаротушения', 'carbon dioxide fire-fighting vehicle', 'fire_safety'),
  ('спринклерлік өрт сөндірудің автоматты жүйесі', 'автоматическая система спринклерного пожаротушения', 'automatic sprinkler fire extinguishing system', 'fire_safety'),
  ('ұнтақпен өрт сөндіру қондырғысы бар өрт сөндіру автомобилі', 'автомобиль пожарный с порошковой установкой пожаротушения', 'dry powder fire-fighting vehicle', 'fire_safety'),
  ('ұнтақпен өрт сөндірудің автоматты жүйесі', 'автоматическая система порошкового пожаротушения', 'automatic dry powder fire extinguishing system', 'fire_safety'),
  ('әуеайлақ өрт сөндіру автомобилі', 'автомобиль аэродромный пожарный', 'airport fire-fighting vehicle', 'fire_safety'),
  ('өрт сөндіру айналмалы су құбыры', 'водопровод пожарный кольцевой', 'ring fire water supply system', 'fire_safety'),
  ('өрт сөндіру жүйесінің ажыратқышы', 'выключатель пожарной системы', 'fire system switch', 'fire_safety'),
  ('өрт сөндіру тұйық су құбыры', 'водопровод пожарный тупиковый', 'dead-end fire water supply system', 'fire_safety'),
  ('ағынды қарық', 'сточная канава', 'gutter', 'industrial_safety'),
  ('суағар науаша', 'водосточный жёлоб', 'gutter', 'industrial_safety'),
  ('су ағының бергіші', 'датчик потока воды', 'waterflow detector', 'fire_safety'),
  ('су айдауыш мұнара', 'водонапорная башня', 'water tower', 'industrial_safety'),
  ('арынды су мұнарасы', 'водонапорная башня', 'water tower', 'industrial_safety'),
  ('қысымды су мұнарасы', 'башня водонапорная', 'water pressure tower', 'industrial_safety'),
  ('су аэрозолі', 'водяной аэрозоль', 'water fog', 'fire_safety'),
  ('аэрозольды суару', 'аэрозольное орошение', 'aerosol irrigation', 'industrial_safety'),
  ('аэрозольмен ластағыш', 'загрязнитель аэрозольный', 'aerosol pollutant', 'industrial_safety'),
  ('су басу шегі', 'граница затопления', 'flood boundary', 'emergencies'),
  ('апатты су басу аймағы', 'зона катастрофического затопления', 'catastrophic flood zone', 'emergencies'),
  ('субұрғыш жыра', 'канава водоотводная', 'drainage ditch', 'industrial_safety'),
  ('су деңгейінің көтерілу биіктігі', 'высота подъема уровня воды', 'water level rise', 'emergencies'),
  ('су деңгейінің көтерілуі', 'подъем уровня воды', 'water level rise', 'emergencies'),
  ('су құбыршы', 'водопроводчик', 'plumber', 'industrial_safety'),
  ('су көзі', 'водоисточник', 'water source', 'fire_safety'),
  ('суқойма, суайдын', 'водоём', 'pond', 'industrial_safety'),
  ('суайдындарын қорғау', 'охрана водоемов', 'protection of water bodies', 'industrial_safety'),
  ('суқоймалардың ластануы', 'загрязнение водоемов', 'water pollution', 'industrial_safety'),
  ('су қоймасы, бөген', 'водохранилище', 'reservoir, impoundment', 'industrial_safety'),
  ('су қоры', 'запас воды', 'water stock', 'industrial_safety'),
  ('жерасты су қоры', 'запасы подземных вод', 'groundwater reserves', 'industrial_safety'),
  ('мемлекеттік су қорының жері', 'земли государственного водного фонда', 'state water fund lands', 'industrial_safety'),
  ('су ресурстарын қорғау', 'охрана водных ресурсов', 'water conservation', 'industrial_safety'),
  ('тасқынсу толқыны', 'паводочная волна', 'flood wave', 'emergencies'),
  ('су теңгерімі', 'водный баланс', 'water balance', 'industrial_safety'),
  ('су шымылдық', 'водная завеса', 'water curtain, water shield', 'fire_safety'),
  ('суағар', 'водосток', 'water drainage', 'industrial_safety'),
  ('суару, суландыру', 'орошение', 'irrigation', 'industrial_safety'),
  ('тамшылатып суару', 'капельное орошение', 'drip irrigation', 'industrial_safety'),
  ('суға төзімділік', 'водостойкость', 'waterproofness', 'industrial_safety'),
  ('сумен қамтамасыз ету', 'водоснабжение', 'water supply', 'industrial_safety'),
  ('ағынды сумен толтыру', 'закачка сточных вод', 'wastewater injection', 'industrial_safety'),
  ('сусыздық', 'безводье', 'low-water period', 'emergencies'),
  ('сусыз шөлдала', 'безводная пустыня', 'arid desert', 'emergencies'),
  ('сутартқыш затпен сусыздандыру', 'обезвоживание водоотнимающим веществом', 'dehydration using a desiccant', 'disaster_medicine'),
  ('оттегімен тыныс алу аппараты', 'аппарат кислородный дыхательный', 'oxygen breathing apparatus', 'rescue_ops'),
  ('тыныс алу аппараты', 'аппарат дыхательный', 'breathing apparatus', 'rescue_ops'),
  ('сүңгуір қоңырауы', 'водолазный колокол', 'diving bell', 'rescue_ops'),
  ('сүңгуір', 'водолаз', 'diver', 'rescue_ops'),
  ('сүңгуір бетпердесі', 'водолазная маска', 'diving mask', 'rescue_ops'),
  ('сүңгуір костюмы', 'водолазный костюм', 'diving suit', 'rescue_ops'),
  ('сүңгуір қайық', 'подводная лодка', 'submarine', 'rescue_ops'),
  ('сүңгуірлік басқыш', 'водолазные трапы', 'diving ladders', 'rescue_ops'),
  ('сығылған ауа', 'сжатый воздух', 'Compressed air', 'industrial_safety'),
  ('сым арқан', 'трос', 'wire rope', 'rescue_ops'),
  ('сымарқан орамы', 'бухта троса', 'coil of rope', 'rescue_ops'),
  ('тұтандыру, оталу', 'зажигание', 'ignition', 'fire_safety'),
  ('шоқтан тұтану', 'зажигание калильное', 'hot-bulb ignition', 'fire_safety'),
  ('ұшқынмен тұтандыру', 'зажигание искровое', 'spark ignition', 'fire_safety'),
  ('сыртқы қауіпсіздік', 'внешняя безопасность', 'external safety', 'civil_defense'),
  ('ұлттық сыртқы қауіпсіздік', 'национальная внешняя безопасность', 'national external security', 'civil_defense'),
  ('өрт сатысы', 'пожарная лестница', 'firefighting ladder, fire ladder', 'fire_safety'),
  ('жылжымалы өрт сөндіру сатысы', 'выдвижная пожарная лестница', 'extension fire ladder', 'fire_safety'),
  ('табиғи-техногендік апат', 'природно-техногенная катастрофа', 'natural and technological disaster', 'emergencies'),
  ('табиғи желдету', 'естественная вентиляция', 'natural ventilation', 'industrial_safety'),
  ('табиғи су көзі', 'естественный водоисточник', 'natural water source', 'fire_safety'),
  ('тактикалық әрекет', 'тактическое действие', 'tactical action', 'coordination'),
  ('тактикалық міндет', 'тактическая задача', 'tactical task', 'coordination'),
  ('арқан', 'канат', 'rope', 'rescue_ops'),
  ('жүкілгіш арқан', 'канат строповой', 'sling rope', 'rescue_ops'),
  ('көтергіш арқан', 'канат подъемный', 'hoisting rope', 'rescue_ops'),
  ('тану белгісі (жетон)', 'опознавательный знак (жетон)', 'identity badge', 'coordination'),
  ('таңу материалы', 'перевязочный материал', 'Dressing material, bandage, dressing', 'disaster_medicine'),
  ('радиотаратқыш', 'радиопередатчик', 'radio transmitter', 'alerting_comms'),
  ('қысқа толқынды таратқыш', 'коротковолновой передатчик', 'shortwave transmitter', 'alerting_comms'),
  ('тасқұлама', 'камнепад', 'avalanche of earth and rocks, rockfall', 'emergencies'),
  ('су басу', 'затопление', 'flooding', 'emergencies'),
  ('жең орағыш катушка', 'катушка рукавная', 'hose reel', 'fire_safety'),
  ('тәуекел аймағы', 'зона риска', 'risk zone', 'coordination'),
  ('тәуекелдерді басқару жүйесі', 'система управления рисками', 'risk management system', 'coordination'),
  ('температура сезбегі', 'датчик температуры', 'temperature sensor, thermal sensor', 'industrial_safety'),
  ('техногендік жер сілкінісі (адам қызметімен бастамашылық етілген)', 'техногенное землетрясение (инициированное деятельностью человека)', 'man-induced earthquake', 'emergencies'),
  ('бекітпе қалпақша', 'запорный клапан', 'flap valve, gate valve, shut-down valve', 'industrial_safety'),
  ('тозу, қажалу (өрт жеңдерінің)', 'истирание (пожарного рукава)', 'chafing, deterioration', 'fire_safety'),
  ('тоқ көзі', 'источник тока', 'source of current supply', 'industrial_safety'),
  ('топографиялық карта', 'топографическая карта', 'topographic map', 'coordination')
;
