-- =============================================================
-- Batch add 2: continued firefighting / rescue / general safety terminology
-- (290 terms). Source: second term list supplied directly by the site
-- owner (kk/ru/en). Rows that exactly duplicated batch 1
-- (0015_add_terms_batch1.sql) or duplicated within this same list were
-- dropped. category assigned by best judgement where not specified.
--
-- HOW TO RUN:
--   Open your Supabase project -> SQL Editor -> paste this file -> Run,
--   after running 0015_add_terms_batch1.sql.
-- =============================================================
insert into public.terms (kk, ru, en, category)
values
  ('жасырын пана', 'укрытие', 'shelter', 'civil_defense'),
  ('массалық қойырлық', 'массовая концентрация', 'mass concentration', 'industrial_safety'),
  ('бастық', 'начальник', 'chief', 'coordination'),
  ('гарнизон бастығы', 'начальник гарнизона', 'Head of the garrison', 'coordination'),
  ('батальон', 'батальон', 'battalion', 'coordination'),
  ('байланыс батальоны', 'батальон связи', 'Communications battalion', 'alerting_comms'),
  ('батпақтану', 'заболачивание', 'waterlog', 'emergencies'),
  ('топырақтың батпақтануы', 'заболачивание почвы', 'waterlogging of the soil', 'emergencies'),
  ('ауатартқы', 'воздухозаборник', 'air inlet', 'industrial_safety'),
  ('бықсып жану', 'горение затяжное', 'prolonged combustion', 'fire_safety'),
  ('ингибитор', 'ингибитор', 'inhibitor', 'industrial_safety'),
  ('ұқыпсыздық', 'небрежность', 'negligence', 'coordination'),
  ('бейберекеттік', 'хаос', 'chaos', 'emergencies'),
  ('конструкциялық бейберекеттік', 'нагромождение конструкционное', '', 'industrial_safety'),
  ('дәліз', 'коридор', '', 'evacuation'),
  ('көлік дәлізі', 'транспортный коридор', 'transport corridor', 'coordination'),
  ('бейнежазба', 'видеозапись', 'video recording', 'coordination'),
  ('жаттығу бейнежазбасы', 'видеозапись тренировки', 'video recording of the workout', 'coordination'),
  ('бейтараптау', 'нейтрализация', 'neutralization', 'industrial_safety'),
  ('кері байланысты бейтараптау', 'нейтрализация обратной связи', 'neutralizing feedback', 'coordination'),
  ('бейтараптауыш', 'нейтрализатор', 'neutralizer', 'industrial_safety'),
  ('бейімделу', 'адаптация', 'adaptation', 'civil_defense'),
  ('жаһандық бейімделу', 'глобальная адаптация', 'global adaptation', 'emergencies'),
  ('бейімдеуіш', 'адаптер', 'adapter', 'industrial_safety'),
  ('электрлік бейімдегіш', 'электрический адаптер', 'electrical adapter', 'industrial_safety'),
  ('бекіту (тиеу-түсіру жұмыстары үшін)', 'крепление', 'bracing', 'industrial_safety'),
  ('бекіту арматурасы', 'арматура запорная', 'shut-off valves', 'industrial_safety'),
  ('өрт-түтін хабарлағыш', 'пожарный извещатель', 'fire alarm system', 'fire_safety'),
  ('белгі жалаушасы', 'флажок сигнальный', 'signal flag', 'alerting_comms'),
  ('сигналдық зымыран', 'сигнальная ракета', 'signal flare', 'alerting_comms'),
  ('белгі, таңба', 'знак', 'symbol, indication, sign, mark, marker; badge', 'coordination'),
  ('сигналдық белгі', 'знак сигнальный', '', 'alerting_comms'),
  ('белгілеу, белгі', 'обозначение', 'signing, symbol', 'coordination'),
  ('цифрлық белгі', 'обозначение цифровое', 'digital designation', 'coordination'),
  ('апатты су тасқыны', 'катастрофические наводнения', 'disastrous flood', 'emergencies'),
  ('жауын-шашын', 'осадки', 'precipitation', 'emergencies'),
  ('атмосфералық жауын-шашын', 'атмосферные осадки', 'Atmospheric precipitation', 'emergencies'),
  ('қиынтұтанатын құрам', 'трудновоспламеняемый состав', 'flame-retardant composition', 'fire_safety'),
  ('барлау ұшу аппараты', 'разведывательный летательный аппарат', 'reconnaissance aircraft', 'rescue_ops'),
  ('өрт кауіпсіздігіне жауапты', 'ответственный за пожарную безопасность', 'person responsible for fire safety', 'fire_safety'),
  ('қауіп, өрт қаупі', 'опасность, опасность пожарная', 'fire hazard', 'fire_safety'),
  ('өкпені қолдан вентиляциялау', 'вентиляция легких искусственная', 'artificial lung ventilation', 'disaster_medicine'),
  ('өртке қарсы меже', 'противопожарная нормирование', 'fire safety standardization', 'fire_safety'),
  ('белсенділік', 'активность', 'activity', 'industrial_safety'),
  ('мемлекеттік шекараны күзету белсенділігі', 'активность охраны государственной границы', 'state border protection activities', 'civil_defense'),
  ('ең аз мәнді үлес белсенділігі', 'активность минимально значимая удельная', 'minimum significant specific activity', 'industrial_safety'),
  ('белсендіргіш', 'активатор', 'promoter, activator', 'industrial_safety'),
  ('белсендіргіш реагент', 'реагент активатор', 'Activator reagent', 'industrial_safety'),
  ('белсендірілген', 'активированный', 'activated', 'industrial_safety'),
  ('белсендірілген кешен', 'комплекс активированный', 'activated complex', 'industrial_safety'),
  ('бензин', 'бензин', 'gas, petrol, gasoline', 'industrial_safety'),
  ('бензин тарату бағаншасы', 'колонка бензораздаточная', 'petrol dispenser', 'industrial_safety'),
  ('бензин қозғалтқышы', 'двигатель бензиновый', 'petrol engine', 'industrial_safety'),
  ('көбік-генераторы', 'пеногенератор', 'foam generator', 'fire_safety'),
  ('датчик', 'датчик', 'sensor, detector', 'industrial_safety'),
  ('датчик торабы', 'узел датчика', 'sensor assembly', 'industrial_safety'),
  ('өрт сөндіргіш жең', 'рукав пожарный', 'fire hose', 'fire_safety'),
  ('жеңқұбыр', 'рукав', 'hose', 'fire_safety'),
  ('жеңқұбыр желісін ұзарту', 'наращивание рукавной линии', 'hose line extension', 'fire_safety'),
  ('ауа-механикалық көбік', 'воздушно-механическая пена', 'air-mechanical foam', 'fire_safety'),
  ('ауа-көбікті оқпан', 'ствол воздушно-пенный', 'air-aspirating foam nozzle', 'fire_safety'),
  ('құтқару күртешесі', 'спасательный жилет', 'life jacket', 'rescue_ops'),
  ('бетті толық жабатын маска', 'полнолицевая маска', 'full face mask', 'rescue_ops'),
  ('тыныс алдыру жеке аппараты', 'аппарат дыхательный индивидуальный', 'self-contained breathing apparatus', 'rescue_ops'),
  ('бета сәулелену', 'бета-излучение', 'beta radiation, beta rays', 'industrial_safety'),
  ('бетон', 'бетон', 'concrete', 'industrial_safety'),
  ('бөліп құйматастау', 'бетонирование раздельное', 'separate concreting', 'industrial_safety'),
  ('вибрациялы құйматастау', 'бетонирование вибрационное', 'vibration concreting', 'industrial_safety'),
  ('қарсы шабуыл, қасбеттік шабуыл (орман өртіне)', 'контратака (на лесной пожар)', 'frontal assault', 'fire_safety'),
  ('әртектілік (беттік) жану', 'горение гетерогенное (поверхностное)', 'heterogeneous (surface) combustion', 'fire_safety'),
  ('бензин буының тұтануы', 'вспышка паров бензина', 'flash of gasoline vapors', 'fire_safety'),
  ('беткі; үсті; бет', 'поверхность', 'surface', 'industrial_safety'),
  ('толық бет', 'поверхность полная', 'full surface', 'industrial_safety'),
  ('асқынсалқындау', 'переохлаждение', 'Hypothermia', 'disaster_medicine'),
  ('қосметалды ішпек', 'вкладыш биметаллический', 'bimetallic bearing shell', 'industrial_safety'),
  ('дәкелітаңғыш', 'бинт', 'bandage', 'disaster_medicine'),
  ('биоотын (өрт жүктемесін бағалау кезіндегі)', 'биотопливо (при оценке пожарной нагрузки)', 'bio-fuel', 'fire_safety'),
  ('биологиялық зақымдану', 'биологическое заражение', 'biological contamination', 'emergencies'),
  ('құрбан', 'жертва', '', 'disaster_medicine'),
  ('өрт құрбаны', 'жертва пожара', 'fire victim', 'fire_safety'),
  ('биологиялық ыдырайтын қалдықтар', 'отходы биологически разложимые', 'biodegradable waste', 'industrial_safety'),
  ('биологиялық ыдырамайтын қалдықтар', 'отходы биологически неразложимые', 'non-biodegradable waste', 'industrial_safety'),
  ('биологиялық (бактериялогиялық) қару', 'биологическое (бактериологическое) оружие', 'biological (bacteriological) weapons', 'emergencies'),
  ('Қазақстан Республикасы Қорғаныс министрлігінің Радиациялық, химиялық және биологиялық қорғау қызметі', 'Служба радиационной, химической и биологической защиты Министерства обороны Республики Казахстан', 'Radiological, Chemical and Biological Protection Service of the Ministry of Defence of the Republic of Kazakhstan', 'civil_defense'),
  ('доза, мөлшер', 'доза', '', 'disaster_medicine'),
  ('уытты доза', 'токсическая доза', 'toxic dose', 'disaster_medicine'),
  ('биомаркер', 'биомаркер', 'biomarker', 'disaster_medicine'),
  ('биомасса', 'биомасса', 'biomass', 'industrial_safety'),
  ('биомассаның өсімі', 'прирост биомассы', 'Biomass growth', 'industrial_safety'),
  ('жылу мөлшері', 'количество тепла', 'amount of heat', 'fire_safety'),
  ('биожаңғыру, биолокация', 'биолокация', 'biolocation', 'industrial_safety'),
  ('биологиялық ластану', 'биологическое загрязнение', 'biochemical contamination', 'emergencies'),
  ('бөліктеу', 'демонтаж', 'dismantling', 'rescue_ops'),
  ('зәулім ғимарат', 'здание высотное', 'high-rise building, high-rise apartment, highrise flats', 'fire_safety'),
  ('блок', 'блок', 'unit, block', 'industrial_safety'),
  ('қуат блогы', 'блок питания', '', 'industrial_safety'),
  ('өртке қарсы қалқан', 'перегородка противопожарная', 'fire partition', 'fire_safety'),
  ('жану жүктемесі', 'нагрузка горючая', 'combustible load', 'fire_safety'),
  ('масштаб, ауқым', 'масштаб', 'scale', 'coordination'),
  ('болжау', 'прогнозирование', 'forecast', 'coordination'),
  ('бомбы', 'бомба', 'bomb', 'emergencies'),
  ('баяу жарылатын бомбы', 'бомба замедленного действия', 'time bomb', 'emergencies'),
  ('боран', 'буран', 'snow storm, blizzard', 'emergencies'),
  ('борт', 'борт', 'board', 'coordination'),
  ('борттық басқару кешені', 'бортовой комплекс управления', 'onboard control system', 'coordination'),
  ('босату', 'опорожнение', 'dumping', 'industrial_safety'),
  ('босқын', 'беженец', 'refugee', 'evacuation'),
  ('босқындар лагері', 'лагерь беженцев', 'refugee camp', 'evacuation'),
  ('кептеліс', 'затор', 'jam, gorge', 'coordination'),
  ('бөген', 'дамба', 'dam', 'industrial_safety'),
  ('бөгесін (уақытша істелген)', 'запруда', 'weir, pond', 'industrial_safety'),
  ('бөгеу', 'заграждение', 'barrage', 'rescue_ops'),
  ('бөлім, бөлімше', 'отделение', 'department, station; compartment, squad', 'coordination'),
  ('бөлімше командирі', 'командир отделения', 'crew commander', 'coordination'),
  ('бөліну (ядроның)', 'деление (ядра)', 'division', 'industrial_safety'),
  ('белдем, арқалық', 'балка', 'joist; davit; beam', 'industrial_safety'),
  ('бригада', 'бригада', 'group, crew, unit, team, squad, gang', 'coordination'),
  ('бу', 'пар', 'vapor, vapour', 'industrial_safety'),
  ('буландырғыш', 'испаритель', 'evaporator', 'industrial_safety'),
  ('булану', 'испарение', 'evaporation', 'industrial_safety'),
  ('бұғаттан шығару', 'деблокирование', 'unblocking, unlocking, deblocking', 'rescue_ops'),
  ('бұзушы', 'нарушитель', 'violator, perpetrator', 'coordination'),
  ('бұзу', 'нарушать, прорвать, взломать', 'to break, to break through, to break in', 'rescue_ops'),
  ('жемірілу', 'абразия', 'abrasion', 'industrial_safety'),
  ('бұзылу, деструкция', 'деструкция', 'decomposition', 'industrial_safety'),
  ('байланыс офицері', 'офицер связи', 'liaison officer, communications officer', 'alerting_comms'),
  ('бітеуіш', 'заглушка', 'cap', 'industrial_safety'),
  ('шымылдық', 'завеса', 'curtain', 'fire_safety'),
  ('жедел жағдайды зерделеу', 'изучение оперативной обстановки', 'studying the operational situation', 'coordination'),
  ('екі қанаттан өрт сөндіру', 'тушения пожара с флангов', 'extinguishing the fire from the flanks', 'fire_safety'),
  ('табиғи дүлей зілзала', 'природное стихийное бедствие', 'natural disaster', 'emergencies'),
  ('бірқалыпты қозғалыс', 'движение равномерное', 'uniform motion', 'industrial_safety'),
  ('бірігу', 'объединение', 'integration; community', 'coordination'),
  ('қож', 'шлак', 'clinker', 'industrial_safety'),
  ('жеке құрам', 'личный состав', 'personnel, staff, crew', 'coordination'),
  ('шұғыл ден қою', 'экстренное реагирование', 'emergency response', 'emergencies'),
  ('алғашқы жіктелу', 'первое спряжение', 'first conjugation', 'coordination'),
  ('өтпелі қосқыш бастиек', 'головка переходная соединительная', 'fire head adapter, connection fitting', 'fire_safety'),
  ('бюллетень', 'бюллетень', 'bulletin', 'alerting_comms'),
  ('бюро', 'бюро', 'bureau', 'coordination'),
  ('вакуумдық сорап', 'вакуумный насос', 'vacuum pump', 'industrial_safety'),
  ('жауынгерлік кезекшілік', 'боевое дежурство', 'combat duty', 'coordination'),
  ('вестибюль', 'вестибюль', 'lobby', 'evacuation'),
  ('газ', 'газ', 'gas, fume', 'industrial_safety'),
  ('газбалон', 'газовый баллон', 'gas cylinder', 'industrial_safety'),
  ('авария кезінде шығатын люк қақпағы', 'крышка люка аварийного покидания', 'emergency escape hatch cover', 'evacuation'),
  ('өрт-түтін хабарлағыш (түтін)', 'извещатель пожарный дымовой', 'smoke detector', 'fire_safety'),
  ('газөлшеуіш', 'газометр', 'gasometer', 'industrial_safety'),
  ('газ тәрізді отындар', 'газообразные топлива', 'gas fuel', 'industrial_safety'),
  ('ұшқынөшіргі', 'искрогаситель', 'spark arrester', 'fire_safety'),
  ('газарна, газ өткізгіш', 'газоход', 'flue', 'industrial_safety'),
  ('газфазалық реакция', 'газофазная реакция', 'gas phase reaction', 'industrial_safety'),
  ('газбен жылыту', 'газообогрев', 'gas firing', 'industrial_safety'),
  ('газдан құтқару ерікті жасақтары', 'добровольные газоспасательные дружины', 'voluntary gas rescue squads', 'rescue_ops'),
  ('газданғандық', 'загазованность', 'gas pollution', 'industrial_safety'),
  ('оттекті оқшаулағыш газқағар', 'кислородно-изолирующий противогаз', 'chemical-oxygen rebreather', 'rescue_ops'),
  ('газсыздандыру', 'дегазация', 'decontamination', 'industrial_safety'),
  ('газтурбиналы қозғалтқыш', 'двигатель газотурбинный', 'gasturbine engine', 'industrial_safety'),
  ('гамма-сәулелендіру', 'гамма-излучение', 'gamma radiation, gamma rays', 'industrial_safety'),
  ('гель', 'гель', 'gel', 'industrial_safety'),
  ('генератор', 'генератор', 'generator', 'industrial_safety'),
  ('геноцид, зұлмат', 'геноцид', 'genocide', 'emergencies'),
  ('геологиялық қима сызығы', 'линия геологического профиля', 'geological profile line', 'industrial_safety'),
  ('географиялық ландшафт', 'ландшафт географический', 'geographic landscape', 'coordination'),
  ('геофизикалық жұмыстар', 'геофизические работы', 'geophysical work', 'coordination'),
  ('гетеротектік', 'гетерогенность', 'heterogeneity', 'industrial_safety'),
  ('гидравлика', 'гидравлика', 'hydraulics', 'industrial_safety'),
  ('гидравликалық домкрат', 'гидравлический домкрат', 'hydraulic jack', 'rescue_ops'),
  ('гидравликалық сорғы', 'гидравлический насос', 'hydraulic pump', 'industrial_safety'),
  ('гидротаратқы', 'гидрораспределитель', 'valve', 'industrial_safety'),
  ('гидранттың ысырмасы', 'задвижка гидранта', 'hydrant gate valve', 'fire_safety'),
  ('гидродинамика', 'гидродинамика', 'hydrodynamics', 'industrial_safety'),
  ('гидродинамикалық авария', 'гидродинамическая авария', 'hydrodynamic accident', 'emergencies'),
  ('гидролиз', 'гидролиз', 'hydrolysis', 'industrial_safety'),
  ('гидрологиялық қадағалау', 'гидрологические наблюдения', 'hydrological observation', 'coordination'),
  ('гидростатика', 'гидростатика', 'hydrostatics', 'industrial_safety'),
  ('гидросфера', 'гидросфера', 'hydrosphere', 'industrial_safety'),
  ('гидроұшақ', 'гидросамолёт', 'flying boat', 'rescue_ops'),
  ('гидрофон', 'гидрофон', 'hydrophone', 'industrial_safety'),
  ('гидроцилиндр', 'гидроцилиндр', 'hydraulic cylinder', 'industrial_safety'),
  ('гипоцентр', 'гипоцентр', 'hypocenter', 'emergencies'),
  ('гонг', 'гонг', 'gong', 'alerting_comms'),
  ('гравитация', 'гравитация', 'gravitation', 'industrial_safety'),
  ('градиент', 'градиент', 'gradient', 'industrial_safety'),
  ('график, кесте', 'график', 'schedule; curve, chart', 'coordination'),
  ('гуманитарлық апат', 'гуманитарная катастрофа', 'humanitarian disaster', 'emergencies'),
  ('гуманитарлық жүк', 'гуманитарный груз', 'humanitarian cargo', 'evacuation'),
  ('ғимарат', 'здание', 'building, facility', 'coordination'),
  ('оттан қорғайтын киім', 'одежда огнезащитная', 'fire-resistant clothing', 'fire_safety'),
  ('сигнал жүйесі', 'система сигнализации', 'alarm system', 'alerting_comms'),
  ('қауіп-қатер дабылы', 'сигнал тревоги', 'alarm signal', 'alerting_comms'),
  ('дабыл сигналы бойынша өрт сөндіруге аттану', 'выезд на пожар по сигналу тревоги', 'responding to a fire alarm', 'fire_safety'),
  ('дағды', 'навык', 'skill', 'coordination'),
  ('даярлық', 'готовность', 'preparedness; willingness, readiness', 'civil_defense'),
  ('апат медицинасының әзірлігі', 'готовность медицины катастроф', 'disaster medicine preparedness', 'disaster_medicine'),
  ('қорғаныш бөгет', 'дамба защитная', 'protective dike', 'industrial_safety'),
  ('сұрапыл дауыл', 'ураган', 'hurricane', 'emergencies'),
  ('тосқауыл', 'мол', 'pier', 'industrial_safety'),
  ('ағаш егу', 'лесопосадка', 'forest planting', 'emergencies'),
  ('дауылды алдын ала ескерту', 'штормовое предупреждение', 'storm warning', 'alerting_comms'),
  ('дауылды жел', 'штормовой ветер', 'gale', 'emergencies'),
  ('дауылды су ағыны', 'штормовой нагон воды', 'storm surge of water', 'emergencies'),
  ('дауысзорайтқыш', 'громкоговоритель', 'loudspeaker, hailer, loud hailer, speaker', 'alerting_comms'),
  ('дауыс қаттылығы', 'громкость звука', 'loudness', 'alerting_comms'),
  ('дезинтеграция (мыс., тасқын салдарынан қозғалыс)', 'дезинтеграция (напр., движения из-за наводнения)', 'disruption', 'emergencies'),
  ('декларация', 'декларация', 'declaration', 'coordination'),
  ('декомпрессия', 'декомпрессия', 'decompression', 'disaster_medicine'),
  ('дем шығару', 'выдох', 'exhalation', 'disaster_medicine'),
  ('демалыс аймағы', 'зона отдыха', 'rest area', 'coordination'),
  ('дем тарту', 'вдох', 'inhalation', 'disaster_medicine'),
  ('демеуқаржы; дотация', 'дотация', 'grant', 'coordination'),
  ('демографиялық', 'демографический', 'demographic', 'coordination'),
  ('әртүрлі ауырлық дәрежесіндегі дене жарақаттары', 'телесные повреждения различной степени тяжести', 'bodily injuries of varying severity', 'disaster_medicine'),
  ('дене, корпус', 'корпус', 'body', 'industrial_safety'),
  ('денсаулық', 'здоровье', 'health', 'disaster_medicine'),
  ('дене әрекеті', 'физическая деятельность', 'physical activity', 'disaster_medicine'),
  ('департамент', 'департамент', 'department', 'coordination'),
  ('үйексіздегіш', 'деполяризатор', 'depolariser', 'industrial_safety'),
  ('депрессия, күйзеліс', 'депрессия', 'depression', 'disaster_medicine'),
  ('тасымалды компьютер', 'портативный компьютер', 'portable computer', 'coordination'),
  ('десорбция (абсорбцияға кері құбылыс)', 'десорбция (явление, обратное абсорбции)', 'desorption', 'industrial_safety'),
  ('детектор', 'детектор', 'detector', 'industrial_safety'),
  ('детектрлеу', 'детектирование', 'detection', 'industrial_safety'),
  ('детонатор, пілте', 'детонатор', 'detonator', 'emergencies'),
  ('детонация, жарылыс', 'детонация', 'detonation', 'emergencies'),
  ('дефлектор', 'дефлектор', 'deflector', 'industrial_safety'),
  ('диаграмма', 'диаграмма', 'diagram', 'coordination'),
  ('диаметр', 'диаметр', 'diameter', 'industrial_safety'),
  ('диапазон', 'диапазон', 'range', 'industrial_safety'),
  ('диафрагма, көкет', 'диафрагма', 'disc, diaphragm', 'industrial_safety'),
  ('дивизия командирі', 'командир дивизии', 'divisional chief', 'coordination'),
  ('дизель қозғалтқыш', 'дизельный двигатель', 'diesel engine', 'industrial_safety'),
  ('динамика, серпін', 'динамика', 'dynamics, behaviour', 'coordination'),
  ('динамит', 'динамит', 'dynamite', 'emergencies'),
  ('дипломатиялық байланыстар', 'дипломатические контакты', 'diplomatic contacts', 'coordination'),
  ('доға', 'дуга', 'arc', 'industrial_safety'),
  ('дозиметр', 'дозиметр', 'dosimeter, survey meter, dose rate meter', 'industrial_safety'),
  ('шарлы қысымтығын', 'шаровой клапан', 'globe valve, ball valve', 'industrial_safety'),
  ('доңғалақ', 'колесо', 'wheel', 'industrial_safety'),
  ('көтергіш кран', 'подъёмный кран', 'crane', 'rescue_ops'),
  ('дроссельді қалқалағыш', 'дроссельная заслонка', 'butterfly valve', 'industrial_safety'),
  ('кәскі', 'каска', 'helmet, head gear', 'rescue_ops'),
  ('еселік', 'кратность', 'expansion', 'fire_safety'),
  ('дыбыс', 'звук', 'sound', 'alerting_comms'),
  ('діңгек', 'мачта', 'mast, tower', 'industrial_safety'),
  ('қатты тіреуіштердегі көпір', 'мост на жёстких опорах', 'dry support bridge', 'evacuation'),
  ('тарту', 'вовлечение', 'incorporation', 'coordination'),
  ('еңбекке жарамсыздық', 'нетрудоспособность', 'disability', 'disaster_medicine'),
  ('еңбекті қорғау', 'охрана труда', 'labour protection', 'industrial_safety'),
  ('мәжбүрлі көші-қон', 'вынужденная миграция', 'forced migration', 'evacuation'),
  ('ерікті өрт сөндіруші', 'добровольный пожарный', 'fire volunteer', 'fire_safety'),
  ('есеп', 'отчёт', 'report, records', 'coordination'),
  ('жаднама', 'памятка', 'reminder list, leaflet', 'coordination'),
  ('ескерту белгісі', 'предупреждающий знак', 'warning sign, precautionary sign', 'alerting_comms'),
  ('өртенбейтін есік', 'противопожарная дверь', 'fire-protective door', 'fire_safety'),
  ('ергенек (кішкене қақпалы есік)', 'калитка', 'wicket door', 'evacuation'),
  ('жабдық', 'оборудование', 'equipment, accessories, machinery, technique, devices, facilities, gear', 'industrial_safety'),
  ('зарарсыздандыру', 'обеззараживание', 'decontamination', 'industrial_safety'),
  ('тұтқырлық', 'вязкость', 'viscosity', 'industrial_safety'),
  ('жайқабылдағыш', 'молниеприёмник', 'lightning protection mast, air terminal', 'industrial_safety'),
  ('жайқорған', 'молниезащита', 'lightning protection', 'industrial_safety'),
  ('жайтартқыш', 'молниеотвод', 'down conductor, lightning conductor', 'industrial_safety'),
  ('келте құбыр', 'патрубок', 'nipple, manifold, fitting', 'industrial_safety'),
  ('теріс хабар', 'дезинформация', 'misinformation', 'alerting_comms'),
  ('ауыстырғыш', 'переходник', 'adapter, reducer', 'industrial_safety'),
  ('кіші жол', 'дорожка', 'walkway, route', 'evacuation'),
  ('жарқыл', 'вспышка', 'flash', 'fire_safety'),
  ('тез тұтанғыш', 'легковоспламеняющийся', 'flammable', 'fire_safety'),
  ('тұтану', 'воспламенение', 'ignition, lighting', 'fire_safety'),
  ('жалюзи', 'жалюзи', 'louver', 'industrial_safety'),
  ('жанарғы', 'горелка', 'burner, torch', 'industrial_safety'),
  ('жанармай', 'горючее', 'fuel', 'industrial_safety'),
  ('жанармай үстеп құю', 'дозаправка топлива', 'refueling', 'industrial_safety'),
  ('жанармай шаны', 'топливный бак', 'fuel tank', 'industrial_safety'),
  ('жанартау', 'вулкан', 'volcano', 'emergencies'),
  ('жанартаутану', 'вулканология', 'volcanology', 'emergencies'),
  ('жанғыш газ', 'горючий газ', 'flammable gas', 'fire_safety'),
  ('тұтанғыштық', 'воспламеняемость', 'inflammability, flammability', 'fire_safety'),
  ('жанғыштық', 'горючесть', 'combustibility, combustible', 'fire_safety'),
  ('жану', 'горение', 'burning, combustion, fire, burn', 'fire_safety'),
  ('жану камерасы', 'камера сгорания', 'combustion chamber', 'industrial_safety'),
  ('жану қарқыны', 'интенсивность горения', 'burning intensity', 'fire_safety'),
  ('жану', 'возгорание', 'burn', 'fire_safety'),
  ('жанып кету', 'выгорать', 'to scorch, to burnout', 'fire_safety'),
  ('қалқалағыш', 'заслонка', 'damper, valve, shutter', 'industrial_safety'),
  ('таңу', 'бинтовать', 'to bandage', 'disaster_medicine'),
  ('жарықтандырғыш', 'осветитель', 'light', 'industrial_safety'),
  ('жарылғыш заттек', 'взрывчатое вещество', 'explosive material, explosive substance', 'emergencies'),
  ('жарылу қаупі бар атмосфера', 'взрывоопасная атмосфера', 'explosive atmosphere', 'emergencies'),
  ('жарылу қаупі', 'взрывоопасность', 'explosion danger, explosion hazard', 'emergencies')
;
