-- =============================================================
-- Batch add 3: continued general/fire-service terminology (137 terms,
-- Ы-П range of the source glossary). Source: third term list supplied
-- directly by the site owner (kk/ru/en). Rows that exactly duplicated
-- earlier batches or duplicated within this same list were merged or
-- dropped. category assigned by best judgement where not specified.
-- One source entry ("оперативті / оценкоперативной / evaluationof") was
-- dropped as garbled/truncated in the original paste.
--
-- HOW TO RUN:
--   Open your Supabase project -> SQL Editor -> paste this file -> Run,
--   after running 0015 and 0016.
-- =============================================================
insert into public.terms (kk, ru, en, category)
values
  ('ықтималдық, мүмкіндік', 'шанс', 'probability, likelihood', 'coordination'),
  ('міндет', 'обязанность', 'duty, responsibility, obligation', 'coordination'),
  ('міндет, міндетті іс, тапсырма, миссия', 'миссия', 'mission', 'coordination'),
  ('міндет; мәселе; мақсат', 'задача', 'task', 'coordination'),
  ('нақты және ықтимал қауіп-қатерлер', 'реальные и потенциальные угрозы', 'palpable hazard', 'emergencies'),
  ('жасақ', 'наряд, отряд', 'tour of duty', 'coordination'),
  ('натурал шама', 'величина натуральная', 'mock-up simulator', 'industrial_safety'),
  ('науқан', 'кампания', 'campaign', 'coordination'),
  ('нашар көрушілік', 'слабовидение', 'poor visibility', 'emergencies'),
  ('негіз', 'основа', 'fundamental, basis, ABC', 'coordination'),
  ('жер сілкінісі', 'землетрясение', 'principal earthquake', 'emergencies'),
  ('негізгі шатыржай', 'базовый лагерь', 'base camp', 'coordination'),
  ('норма, ереже, қағида', 'норма', 'standard, regulation, norm', 'coordination'),
  ('нормалар', 'нормы', 'codes, standards, regulations', 'coordination'),
  ('нөмір', 'номер', 'number', 'coordination'),
  ('нұсқа, түр', 'вариант', 'option', 'coordination'),
  ('нұсқаухат', 'инструктаж', 'instruction, briefing', 'coordination'),
  ('нұсқаушы', 'инструктор', 'instructor', 'coordination'),
  ('нығайтқыш', 'крепёж', 'belay', 'rescue_ops'),
  ('нысан', 'объект', 'object', 'coordination'),
  ('озон тесігі', 'дыра озоновая', 'ozone depletion', 'emergencies'),
  ('окклюзия', 'окклюзия', 'occlusion', 'disaster_medicine'),
  ('оқиға бойынша деректер', 'данные по происшествию', 'accident data', 'coordination'),
  ('оқиға болған жер', 'место происшествия', 'occurrence of accident, accident site', 'coordination'),
  ('оқиға орны', 'место происшествия', 'accident location, incident location', 'coordination'),
  ('оқиға уақыты', 'время происшествия', 'Incident occurred time', 'coordination'),
  ('оқшауланған', 'изолированный', 'isolated', 'industrial_safety'),
  ('оқшаулау', 'изоляция', 'isolation', 'industrial_safety'),
  ('оқшаулау уақыты', 'время локализации', 'holding time', 'fire_safety'),
  ('оқшаулаушы материал', 'изолирующий материал', 'insulating material', 'industrial_safety'),
  ('оқыту, үйрету', 'обучение', 'training, education', 'coordination'),
  ('оператор', 'оператор', 'operator', 'coordination'),
  ('операторлық', 'операторская', 'operating room', 'coordination'),
  ('опырылу аймағы', 'зона обрушений', 'collapse zone', 'emergencies'),
  ('опырылу, опырылып түсу', 'обвал', 'collapse', 'emergencies'),
  ('опырылымдық жерсілкіну', 'обвальное землетрясение', 'collapse earthquake', 'emergencies'),
  ('орман аймағы', 'зона лесов', 'forested area', 'emergencies'),
  ('орман пайдалану', 'лесопользование', 'forest management', 'industrial_safety'),
  ('ормандар картасы', 'карта лесов', 'forest map', 'coordination'),
  ('орманды қалпына келтіру', 'лесовосстановление', 'reforestation', 'industrial_safety'),
  ('орманды өрттен қорғау', 'защита лесов от пожара', 'forest fire protection', 'fire_safety'),
  ('орнықты жану', 'устойчивое горение', 'sustained combustion', 'fire_safety'),
  ('орнын ауыстыру', 'передислокация', 'redevelopment, redeployment', 'coordination'),
  ('орнын толтыру', 'возмещение', 'indemnity, allowance, reimbursement, compensation', 'coordination'),
  ('орнына бұқаралық ақпарат құралдарына кіруге мүмкіндік беру (төтенше жағдай)', 'предоставить СМИ доступ к месту (ЧС)', 'to allow media access to scene', 'alerting_comms'),
  ('орындау', 'выполнение', 'performance; processing', 'coordination'),
  ('от', 'огонь', 'light, flame, fire', 'fire_safety'),
  ('от алу, тұтану', 'вспышка', 'flash, spark, flare; outbreak', 'fire_safety'),
  ('от ұшқыны', 'искра от пожара', 'fire-producing spark', 'fire_safety'),
  ('отқа төзімді', 'огнестойкий', 'fireproof, ignition-proof, incombustible', 'fire_safety'),
  ('отқа төзімді материал', 'огнеупорный материал', 'refractory', 'fire_safety'),
  ('отқа төзімді саз', 'огнеупорная глина', 'fire clay', 'fire_safety'),
  ('отқа төзімділік', 'огнестойкость', 'fire stability, flame stability, flame resistance', 'fire_safety'),
  ('отқа төзімді өңдеу', 'огнезащитная обработка', 'flame retardant treatment', 'fire_safety'),
  ('оттек', 'кислород', 'oxygen', 'industrial_safety'),
  ('оттек баллоны', 'кислородный баллон', 'oxygen bottle', 'rescue_ops'),
  ('оттекпен қанықтыру', 'насыщение кислородом', 'oxygenation', 'disaster_medicine'),
  ('тыныс алу аппараты', 'регенеративный дыхательный аппарат', 'breathing apparatus', 'rescue_ops'),
  ('оттық; шақпақ', 'зажигалка', 'lighter', 'fire_safety'),
  ('офицер', 'офицер', 'officer', 'coordination'),
  ('ошақ', 'очаг', 'fireplace; base', 'fire_safety'),
  ('өзара көмек', 'взаимопомощь', 'mutual assistance, buddy-aid', 'rescue_ops'),
  ('өзгерту; өзгеру', 'изменение', 'change, evolution, variation, difference', 'coordination'),
  ('өздігінен жанатын зат', 'самовоспламеняющееся вещество', 'pyrophorus', 'fire_safety'),
  ('өздігінен жану', 'самостоятельное горение', 'afterglow', 'fire_safety'),
  ('өзіндік салқындату', 'естественное охлаждение', 'natural cooling', 'industrial_safety'),
  ('өкпе желдетілуі', 'вентиляция лёгких', 'respiration', 'disaster_medicine'),
  ('өлгендер саны', 'количество умерших', 'number of deaths', 'disaster_medicine'),
  ('өлшем, өлшемшарт, критерий', 'критерий', 'criterion', 'coordination'),
  ('өлшем; өлшеу', 'мера', 'gauging', 'industrial_safety'),
  ('өлшеу', 'измерение', 'gauging, measurement', 'industrial_safety'),
  ('өлшеу', 'измерять', 'to gage, to gauge', 'industrial_safety'),
  ('өлшеуіш', 'измеритель', 'meter', 'industrial_safety'),
  ('өмір', 'жизнь', 'life', 'disaster_medicine'),
  ('өмір қауіпсіздігі', 'безопасность жизни', 'safety of life', 'civil_defense'),
  ('өміршеңдік', 'выживаемость', 'survivability', 'disaster_medicine'),
  ('өндіріс қауіпсіздігі', 'безопасность производства', 'production safety', 'industrial_safety'),
  ('өндірістік авария', 'промышленная авария', 'industrial accident', 'industrial_safety'),
  ('өндірістік апат', 'производственная авария', 'technological accident', 'emergencies'),
  ('өндірістік қызмет', 'промышленная деятельность', 'industrial activities', 'industrial_safety'),
  ('өңдеу', 'обработка', 'treatment', 'industrial_safety'),
  ('өрт аймағы', 'зона пожара', 'area of fire, fire area, fire zone, part of fire', 'fire_safety'),
  ('өрт гидранты', 'пожарный гидрант', 'hydrant, fire hydrant', 'fire_safety'),
  ('өрт депосы', 'пожарное депо', 'fire house', 'fire_safety'),
  ('өрт жағдайы', 'обстоятельства пожара', 'circumstances of a fire', 'fire_safety'),
  ('өрт жалыны', 'пламя пожара', 'flame from fire', 'fire_safety'),
  ('өрт қарқыны', 'интенсивность пожара', 'intensity of fire, fire intensity, fire severity', 'fire_safety'),
  ('өрт қарқыны', 'масштаб пожара', 'level of fire', 'fire_safety'),
  ('өрт қаупі', 'опасность пожара', 'fire peril', 'fire_safety'),
  ('өрт қаупі', 'пожарная опасность', 'fire hazard, fire danger', 'fire_safety'),
  ('өрт қауіпсіздігі', 'пожарная безопасность', 'fire safety', 'fire_safety'),
  ('өрт қауіпсіздігін қамтамасыз ету', 'обеспечение пожарной безопасности', 'fire-safety management', 'fire_safety'),
  ('өрт нәтижесінде қоршаған ортаның ластануы', 'загрязнение окружающей среды в результате пожара', 'pollution from fire', 'fire_safety'),
  ('өрт ошағы', 'очаг пожара', 'area of fire origin, fire initiation zone', 'fire_safety'),
  ('өрт ошағын табу', 'обнаружение очага пожара', 'discovery of fire start', 'fire_safety'),
  ('өрт хабарлағышы', 'пожарный извещатель', 'combustion detector', 'fire_safety'),
  ('өрт сәулелендіру (жылулық)', 'излучение пожара (тепловое)', 'fire radiation', 'fire_safety'),
  ('өрт сөндіргіш', 'огнетушитель', 'extinguisher, fire extinguisher, fire apparatus', 'fire_safety'),
  ('өрт сөндіргіш кеме', 'пожарный катер', 'fireboat, fire fighting boat, fire float', 'fire_safety'),
  ('өрт сөндіргіш көбік', 'огнетушащая пена', 'extinguishing foam, finished foam, fire-fighting foam', 'fire_safety'),
  ('өрт сөндіру бөлімі', 'часть пожарная', 'firing squad', 'fire_safety'),
  ('өрт сөндіру депосы', 'пожарное депо', 'fire station', 'fire_safety'),
  ('өрт сөндіру жабдықтары', 'пожарное оборудование', 'fire equipment', 'fire_safety'),
  ('өрт сөндіру құралы', 'средства пожаротушения', 'fire tool', 'fire_safety'),
  ('өрт сөндіру сорғысы', 'пожарный насос', 'fire pump, syringe', 'fire_safety'),
  ('өрт сөндіруші', 'огнеборец', 'firefighter', 'fire_safety'),
  ('өрт сөндіруші газ', 'огнетушащий газ', 'smothering gas', 'fire_safety'),
  ('өрт сөндірушілер наряды (қаруланған), өрт сөндірушілер жасағы (қаруланған)', 'пожарный наряд (с вооружением)', 'attendance', 'fire_safety'),
  ('өрт сөндірушінің жауынгерлік киімі', 'боевая одежда пожарного', 'firefighter''s uniform, fire-fighter gear', 'fire_safety'),
  ('өрт сөндірушінің киімі (қорғаныс)', 'боевая одежда пожарного', 'fire tunic', 'fire_safety'),
  ('өрт хабарлағышы', 'пожарный оповещатель', 'fire detector, fire speaker, fire-alarm signalling device', 'fire_safety'),
  ('өрт шелегі', 'пожарное ведро', 'fire pail, fire bucket', 'fire_safety'),
  ('өрт ісі', 'пожарное дело', 'fire matter, firemanship', 'fire_safety'),
  ('өртеу пеші', 'печь отжигательная', 'firing', 'industrial_safety'),
  ('өртке қарсы арық (орман өртін сөндіру кезіндегі)', 'противопожарная канава (при тушении лесного пожара)', 'fire trench', 'fire_safety'),
  ('өртке қарсы бүркеу', 'противопожарная завеса', 'fire curtain', 'fire_safety'),
  ('өртке қарсы бүркеу', 'противопожарная заслонка', 'fire curtain', 'fire_safety'),
  ('өртке қарсы қорғау', 'противопожарная защита', 'fire protection, fire control', 'fire_safety'),
  ('өртке қарсы тосқауыл', 'противопожарный барьер', 'anti-fire barrier, fire break', 'fire_safety'),
  ('өрттен қорғау', 'пожарная охрана', 'fire defence', 'fire_safety'),
  ('өрт-техникалық жабдықтар', 'пожарно-техническое вооружение', 'fire-control equipment', 'fire_safety'),
  ('өрт-техникалық тексеру', 'пожарно-техническое инспектирование', 'fire inspection', 'fire_safety'),
  ('өртті зерттеу', 'исследование пожара', 'fire research', 'fire_safety'),
  ('өртті оқшаулау', 'локализация пожара', 'fire stabilization', 'fire_safety'),
  ('өткізбейтін', 'непроницаемый', 'impermeable', 'industrial_safety'),
  ('өтпелі жалғастырғыш', 'переходная муфта', 'adapter', 'industrial_safety'),
  ('өшу', 'затухание', 'attenuation, decay', 'fire_safety'),
  ('пайдаланылған газдар', 'выхлопные газы', 'exhaust fumes', 'industrial_safety'),
  ('пакет', 'пакет', 'packet', 'coordination'),
  ('паллета', 'паллета', 'pallet', 'industrial_safety'),
  ('пандемия, індет', 'пандемия', 'pandemics', 'emergencies'),
  ('панель', 'панель', 'panel; plate', 'industrial_safety'),
  ('параметр', 'параметр', 'parameter, value', 'industrial_safety'),
  ('парапсихолог', 'парапсихолог', 'parapsychologist', 'disaster_medicine'),
  ('парашют', 'парашют', 'parachute', 'rescue_ops'),
  ('пәтер', 'квартира', 'flat', 'coordination'),
  ('пейджер', 'пейджер', 'pager', 'alerting_comms')
;
