-- =============================================================
-- Batch add 4: fire-technical terminology (108 terms, Ж-К range of the
-- source glossary). Source: "Қазақша-орысша-ағылшынша өрт-техникалық
-- сөздігі" (Kazakh-Russian-English fire and technical dictionary,
-- Kokshetau, 2021) supplied by the site owner as a .docx table.
-- category values map to CATEGORIES keys in src/i18n/translations.js;
-- assigned by best judgement where the source didn't specify one.
--
-- Cleanup applied while extracting from the source table: merged-cell
-- artifacts (kk text duplicated across grid columns) were deduplicated;
-- rows with only the Kazakh term (Russian identical to Kazakh — a
-- borrowed technical word) keep the same value in kk and ru; obvious
-- source typos were corrected (e.g. "жаунгерлік" -> "жауынгерлік",
-- "веделение" -> "выделение", Cyrillic "с" in "сondensate" -> Latin
-- "condensate"); one bare "жер" (too generic to be useful standalone)
-- and one near-duplicate of an existing batch-2 entry
-- ("көбік-генераторы") were dropped.
--
-- HOW TO RUN:
--   Open your Supabase project -> SQL Editor -> paste this file -> Run,
--   after running 0015, 0016 and 0017.
-- =============================================================
insert into public.terms (kk, ru, en, category)
values
  ('жарылысқа төзімділік', 'взрывоустойчивость', 'explosion-resistant', 'industrial_safety'),
  ('жарылыстан қорғау', 'взрывозащищенность', 'flameproof', 'industrial_safety'),
  ('жасақ (ерікті жасақ)', 'добровольная дружина', 'brigade', 'rescue_ops'),
  ('жасақ (арнайы жасақ)', 'отряд (специального назначения)', 'group, unit, team, squad, squadron', 'rescue_ops'),
  ('жауапкершілік', 'ответственность', 'accountability; responsibility; liability', 'coordination'),
  ('құрғақшылық', 'засуха', 'drought, drying', 'emergencies'),
  ('жауын-шашын өлшегіш', 'осадкоизмеритель', 'rain gauge, rain gage', 'industrial_safety'),
  ('жедел даярлық', 'оперативная подготовка', 'operational readiness', 'coordination'),
  ('жедел-жауынгерлік топ', 'оперативно-боевая группа', 'operational team, command staff', 'rescue_ops'),
  ('жеке тұлға', 'физическое лицо, личность', 'individual, identity', 'coordination'),
  ('жеке іс', 'личное дело', 'personnel record file', 'coordination'),
  ('желдеткіш', 'вентилятор', 'fan, ventilator, blower', 'rescue_ops'),
  ('желдету', 'выветривание', 'ventilation, aeration', 'industrial_safety'),
  ('желдету', 'вентиляция', 'ventilation', 'industrial_safety'),
  ('жең орағыш катушка (өртке қарсы қызм.)', 'катушка рукавная', 'hose reel', 'fire_safety'),
  ('желдетілетін орынжай', 'помещение вентилируемое', 'ventilated', 'industrial_safety'),
  ('жемірілу', 'абразия, коррозия', 'corrosion', 'industrial_safety'),
  ('жерқазғыш', 'землечерпалка', 'dredge, digger', 'rescue_ops'),
  ('жерасты сулары мен газдарының жасы', 'возраст подземных вод и газов', 'age of groundwater and gases', 'industrial_safety'),
  ('жерді пайдалану', 'использование земли, землепользование', 'land use', 'coordination'),
  ('жинақтағыш (көлік ж/е қат. жол.)', 'коллектор', 'reservoir', 'industrial_safety'),
  ('жол', 'дорога, путь', 'way, route, road', 'evacuation'),
  ('жол белгісі (көлік ж/е қат. жол.)', 'знак дорожный', 'road symbol', 'evacuation'),
  ('жол талғамайтын көлік', 'вездеход', 'all-terrain vehicle', 'rescue_ops'),
  ('жолдар картасы (қатынас жолдары картасы)', 'карта дорог (карта путей сообщения)', 'route map', 'evacuation'),
  ('жолды жабу (төтенше жағдай кезінде)', 'закрытие, перекрытие дороги (при ЧС)', 'road closure', 'evacuation'),
  ('журнал', 'журнал', 'journal', 'coordination'),
  ('жұқпалы аурулар', 'болезни инфекционные', 'contagious diseases', 'disaster_medicine'),
  ('жұмылдыру', 'мобилизация', 'mobilization, mobilizing', 'coordination'),
  ('жүк', 'груз', 'cargo, freight, goods', 'coordination'),
  ('жүк автомобилі', 'автомобиль грузовой', 'vehicle for cargo, truck, lorry', 'rescue_ops'),
  ('жүк көтергіштік', 'грузоподъёмность', 'load capacity, lifting capacity', 'industrial_safety'),
  ('жүргізуші', 'водитель', 'driver', 'coordination'),
  ('жылжымалы сатысы (өрт сөндірушілердің)', 'выдвижная лестница (пожарная)', 'extension ladder', 'fire_safety'),
  ('жылу бөліну', 'выделение тепла', 'thermal pulse', 'industrial_safety'),
  ('жылу теңгерімі', 'тепловой баланс', 'heat balance', 'industrial_safety'),
  ('залалсыздандыру', 'дезинфекция', 'disposal', 'disaster_medicine'),
  ('залалсыздандыру; зарарсыздандыру; ауру жұқпайтындай қылу', 'обеззараживание', 'decontamination, disinfection', 'disaster_medicine'),
  ('заң', 'закон', 'law, act', 'coordination'),
  ('заңсыз әрекет', 'действие неправомерное', 'unlawful act', 'coordination'),
  ('зарарсыздандыру; дезинфекция; дезинфекциялау', 'дезинфекция', 'disinfection', 'disaster_medicine'),
  ('зарин (уландыратын заттек)', 'зарин (ОВ)', 'sarin', 'industrial_safety'),
  ('заряд', 'заряд', 'charge', 'industrial_safety'),
  ('зерттеуші', 'исследователь', 'researcher', 'coordination'),
  ('зертхана', 'лаборатория', 'laboratory', 'industrial_safety'),
  ('зиянды заттектер', 'вредные вещества', 'noxious substance', 'industrial_safety'),
  ('зияндылық', 'вредность', 'hazard', 'industrial_safety'),
  ('зілбалға', 'кувалда', 'hammer, sledge hammer', 'rescue_ops'),
  ('изотерма', 'изотерма', 'isotherm, isothermal line', 'industrial_safety'),
  ('импульс', 'импульс', 'pulse, impact, surge', 'industrial_safety'),
  ('инерттілік', 'инертность', 'inert', 'industrial_safety'),
  ('инжектор', 'инжектор', 'injector', 'industrial_safety'),
  ('инженерлік қамсыздандыру', 'инженерное обеспечение', 'engineering provision', 'coordination'),
  ('инспектор', 'инспектор', 'surveyor', 'coordination'),
  ('инспектор', 'инспектор', 'inspector', 'coordination'),
  ('институт', 'институт', 'institute, institution', 'coordination'),
  ('инфрақұрылым', 'инфраструктура', 'infrastructure', 'coordination'),
  ('инфрақызыл сәулелену', 'инфракрасное излучение', 'infra-red rays, infrared radiation', 'industrial_safety'),
  ('иприт (уландырғыш зат)', 'иприт (горчичный газ)', 'mustard gas', 'industrial_safety'),
  ('иірім', 'водоворот', 'vortex', 'emergencies'),
  ('кавитация', 'кавитация', 'cavitation', 'industrial_safety'),
  ('калориметрия', 'калориметрия', 'calorimetry', 'industrial_safety'),
  ('калория', 'калория', 'calorie', 'industrial_safety'),
  ('камуфляж', 'камуфляж', 'camouflage', 'coordination'),
  ('кандела (жарық күшінің өлшем бірлігі)', 'кандела (единица силы света)', 'candela', 'industrial_safety'),
  ('карабин (құтқару құрылғысына арналған)', 'карабин (для спасательного устройства)', 'karabiner, snap hook', 'rescue_ops'),
  ('кассета', 'кассета', 'rack', 'industrial_safety'),
  ('кәсіби бейімделу', 'адаптация профессиональная', 'professional adaptation', 'coordination'),
  ('кәсіби апаттық-құтқару қызметі', 'профессиональная аварийно-спасательная служба', 'professional emergency rescue service', 'rescue_ops'),
  ('кедергі, қоршау', 'ограждение', 'fence, guardrail, enclosure, barrier, shield', 'industrial_safety'),
  ('кезекші', 'дежурный', 'watcher, watchman', 'coordination'),
  ('кезекшілік жауынгерлік', 'боевое дежурство', 'combat duty', 'coordination'),
  ('кейінгі дүмпу', 'афтершок', 'aftershock, earthquake aftershock', 'emergencies'),
  ('келісімшарт', 'контракт', 'contract', 'coordination'),
  ('кеме', 'корабль, судно', 'scooter, boat', 'rescue_ops'),
  ('кептіру', 'высушивание, сушка', 'drying', 'industrial_safety'),
  ('кинетика', 'кинетика', 'kinetics', 'industrial_safety'),
  ('киіз', 'кошма', 'fire blanket', 'fire_safety'),
  ('клаксон', 'клаксон', 'klaxon', 'alerting_comms'),
  ('коагуляция', 'коагуляция', 'coagulation', 'industrial_safety'),
  ('код', 'код', 'code', 'coordination'),
  ('кокарда', 'кокарда', 'badge', 'coordination'),
  ('коктейл', 'коктейль', 'cocktail', 'fire_safety'),
  ('коллапс', 'коллапс', 'collapse', 'emergencies'),
  ('коллектор', 'коллектор', 'manifold', 'industrial_safety'),
  ('коллоидты', 'коллоидный', 'colloid', 'industrial_safety'),
  ('команда', 'команда', 'crew, group, team, squad, company, brigade', 'rescue_ops'),
  ('комиссар', 'комиссар', 'adjuster', 'coordination'),
  ('комиссия', 'комиссия', 'commission', 'coordination'),
  ('комитет', 'комитет', 'committee, board', 'coordination'),
  ('компрессор', 'компрессор', 'compressor', 'industrial_safety'),
  ('компьютер', 'компьютер', 'computer', 'coordination'),
  ('конвективтік', 'конвективная', 'convective heat', 'industrial_safety'),
  ('конвекция', 'конвекция', 'convection', 'industrial_safety'),
  ('конвертер', 'конвертер', 'converter', 'industrial_safety'),
  ('конденсат', 'конденсат', 'condensate', 'industrial_safety'),
  ('контейнер', 'контейнер', 'container', 'industrial_safety'),
  ('контур', 'контур', 'path, circuit, envelope', 'industrial_safety'),
  ('конус', 'конус', 'cone', 'industrial_safety'),
  ('конфигурация', 'конфигурация', 'form, configuration', 'coordination'),
  ('концентрат', 'концентрат', 'concentrate', 'industrial_safety'),
  ('көбік', 'пена', 'foam', 'fire_safety'),
  ('көзбен шолып тексеру', 'проверка визуальная', 'visual inspection', 'coordination'),
  ('көлем', 'объём', 'volume, gallonage', 'industrial_safety'),
  ('көпірдің жүк көтерімділігі', 'грузоподъёмность моста', 'bridge load capacity', 'industrial_safety'),
  ('көрік', 'горн', 'horn', 'alerting_comms'),
  ('көтергіш кран', 'подъёмный кран', 'crane', 'rescue_ops'),
  ('көшкін жабдықтары', 'лавинное снаряжение', 'avalanche equipment', 'rescue_ops')
;
