-- =============================================================
-- Batch add 7: terms starting with «І» (114 terms), supplied by the site
-- owner as a kk / ru / en table pasted in chat.
-- category values map to CATEGORIES keys in src/i18n/translations.js;
-- assigned by best judgement (the source didn't specify one), matching
-- the categories of similar terms already in the base. Records management,
-- legal and HR terms go to coordination; search-and-rescue to rescue_ops;
-- drilling / engineering to industrial_safety; IT / search systems and
-- connectors to alerting_comms.
--
-- Cleanup applied while extracting from the source table: spaces lost
-- when copying were restored in both the Kazakh and the English columns
-- ("іздеуалгоритмі" -> "іздеу алгоритмі", "searchalgorithm" -> "search
-- algorithm"…); English lower-cased except proper names; small fixes:
-- en "запуск" -> "start / launch", "критерий поисковые" -> "критерии
-- поисковые", "заструг" -> "заструга", "ішкі мембран" -> "ішкі мембрана",
-- "IIгруппы" -> "II группы".
-- Skipped because they are already in the base: «ілгек бақан»,
-- «ізгілік көмек», «іркіліс», «іріктемелі шақыру», «індет»,
-- «істікшелі қосылыс», «істікшелі ағытпа», «істікшелі қосқыш».
-- Source duplicates added once: «ішкі бақылау» (внутренний контроль /
-- контроль внутренний), «ішкі мониторинг» (внутренний мониторинг /
-- мониторинг внутренний).
--
-- Applied with: npx supabase db query --linked -f supabase/migrations/0026_add_terms_batch7.sql
-- =============================================================
insert into public.terms (kk, ru, en, category)
values
  ('іздеу алгоритмі', 'алгоритм поиска', 'search algorithm', 'alerting_comms'),
  ('іргелі талдау', 'анализ фундаментальный', 'fundamental analysis', 'coordination'),
  ('іргетас асты арқалығы', 'балка подфундаментная', 'sub-foundation beam', 'industrial_safety'),
  ('ішкі жылу бөгеуілі', 'барьер тепловой внутренний', 'internal thermal barrier', 'industrial_safety'),
  ('ілкі нобай', 'бета-версия', 'beta version', 'alerting_comms'),
  ('ішек ауыруы', 'боли кишечные', 'intestinal pain', 'disaster_medicine'),
  ('іргетас бұраны', 'болт фундаментный', 'foundation bolt', 'industrial_safety'),
  ('іздеу бұрғылауы', 'бурение поисковое', 'exploratory drilling', 'industrial_safety'),
  ('іске қосу / кіру деректері', 'ввод / вводные данные', 'input / input data', 'alerting_comms'),
  ('іске қосу', 'ввод в действие', 'commissioning; putting into operation; implementation', 'industrial_safety'),
  ('ілініс салмағы', 'вес цепной', 'chain weight', 'industrial_safety'),
  ('іліну', 'вис', 'hang', 'rescue_ops'),
  ('ішпек', 'вкладыш', 'liner', 'industrial_safety'),
  ('ішкі сәулелену', 'внутреннее облучение', 'internal irradiation', 'industrial_safety'),
  ('ішкі орын ауыстыру', 'внутреннее перемещение', 'internal movement', 'evacuation'),
  ('ішкі қасиет', 'внутреннее свойство', 'intrinsic property', 'industrial_safety'),
  ('ішкі үйкеліс', 'внутреннее трение', 'internal friction', 'industrial_safety'),
  ('ішкі әскерлер', 'внутренние войска', 'Internal Troops', 'civil_defense'),
  ('ішкі құжаттар', 'внутренние документы', 'internal documents', 'coordination'),
  ('ішкі күштер', 'внутренние силы', 'internal forces', 'industrial_safety'),
  ('ішкі қарулы жанжал', 'внутренний вооруженный конфликт', 'internal armed conflict', 'emergencies'),
  ('ішкі диаметр', 'внутренний диаметр', 'inner diameter', 'industrial_safety'),
  ('ішкі құжат', 'внутренний документ', 'internal document', 'coordination'),
  ('ішкі бақылау', 'внутренний контроль', 'internal control', 'coordination'),
  ('ішкі мониторинг', 'внутренний мониторинг', 'internal monitoring', 'coordination'),
  ('ішкі трафик', 'внутренний трафик', 'internal traffic', 'alerting_comms'),
  ('ішкі диффузия', 'внутренняя диффузия', 'internal diffusion', 'industrial_safety'),
  ('ішкі мембрана', 'внутренняя мембрана', 'inner membrane', 'industrial_safety'),
  ('ішкі миграция', 'внутренняя миграция', 'internal migration', 'evacuation'),
  ('іс құжаттарының ішкі тізімдемесі', 'внутренняя опись документов дела', 'internal inventory of case documents', 'coordination'),
  ('ішкі есеп беру', 'внутренняя отчетность', 'internal reporting', 'coordination'),
  ('ішкі шаруашылық бақылау', 'внутрихозяйственный контроль', 'internal control', 'coordination'),
  ('індеттің бұрқете түсуі', 'вспышка эпидемическая', 'epidemic outbreak', 'disaster_medicine'),
  ('іріктемелі бақылау', 'выборочный контроль', 'selective inspection', 'coordination'),
  ('іздеу ұңғымаларын терең бұрғылау', 'глубокое бурение поисковых скважин', 'deep exploratory drilling', 'industrial_safety'),
  ('ізгілендіру', 'гуманизация', 'humanization', 'coordination'),
  ('іскерлік атақ-абырой, іскерлік бедел', 'деловая репутация', 'business reputation', 'coordination'),
  ('іс жүргізу', 'делопроизводство', 'records management / office administration', 'coordination'),
  ('іс-әрекет, қызмет', 'деятельность', 'activity', 'coordination'),
  ('ішке қолдану үшін', 'для внутреннего применения', 'for internal use', 'disaster_medicine'),
  ('ілеспе құжат', 'документ сопроводительный', 'accompanying document', 'coordination'),
  ('ілкім құжат', 'документ черновой', 'draft document', 'coordination'),
  ('іс жүргізудің бірыңғай мемлекеттік жүйесі', 'единая государственная система делопроизводства', 'Unified State System of Records Management', 'coordination'),
  ('іздестіру сұрау салу', 'запрос поисковый', 'search query', 'alerting_comms'),
  ('іске қосу', 'запуск', 'start / launch', 'industrial_safety'),
  ('ірі тісті сүргі', 'заструга', 'sastrugi', 'emergencies'),
  ('іздеу және барлау шығындары', 'затраты на поиски и разведку', 'exploration and appraisal costs', 'industrial_safety'),
  ('іштенілу', 'зацеп', 'ladder latch / rung lock', 'fire_safety'),
  ('ішкі ілініс', 'зацепление внутреннее', 'internal meshing', 'industrial_safety'),
  ('ішкі буын', 'звено внутреннее', 'inner link', 'industrial_safety'),
  ('іркінді сулар аймағы', 'зона застойных вод', 'stagnant water zone', 'emergencies'),
  ('ізденіс жұмыстары', 'изыскательские работы', 'surveying works', 'industrial_safety'),
  ('І және ІІ топтағы мүгедектер', 'инвалиды I и II группы', 'persons with Group I and Group II disabilities', 'disaster_medicine'),
  ('істердің жеке номенклатурасы', 'индивидуальная номенклатура дел', 'individual file plan', 'coordination'),
  ('іздеу (талап қою, іздену, қуыну)', 'иск', 'lawsuit', 'coordination'),
  ('ішкі сақина', 'кольцо внутреннее', 'inner ring', 'industrial_safety'),
  ('іссапар', 'командировка', 'business trip', 'coordination'),
  ('іздеу өлшемшарттары', 'критерии поисковые', 'search criteria', 'alerting_comms'),
  ('ірі өнеркәсіптік өндіріс', 'крупное промышленное производство', 'large-scale industrial production', 'industrial_safety'),
  ('ірі қара', 'крупный рогатый скот', 'cattle', 'coordination'),
  ('істі ашу шаралары', 'меры вскрытия дела', 'measures to uncover the facts of the case', 'coordination'),
  ('іскери салық', 'налог деловой', 'business tax', 'coordination'),
  ('іс номенклатурасы', 'номенклатура дел', 'nomenclature of files', 'coordination'),
  ('іс нөмірі', 'номер дела', 'case number', 'coordination'),
  ('істер тізімдемесі', 'опись дел', 'file inventory / records inventory', 'coordination'),
  ('із таңбалар', 'отпечатки', 'fingerprints', 'coordination'),
  ('істі ресімдеу', 'оформление дела', 'file preparation / file binding and processing', 'coordination'),
  ('істерді тігу', 'подшивка дел', 'binding of files', 'coordination'),
  ('іздеу', 'поиск', 'search', 'rescue_ops'),
  ('іздеу тобы', 'поисковая группа', 'search team', 'rescue_ops'),
  ('іздестіру бағалау ұңғымасы', 'поисковая оценочная скважина', 'exploratory appraisal well', 'industrial_safety'),
  ('іздеу жүйесі', 'поисковая система', 'search engine', 'alerting_comms'),
  ('ізкескіш ит', 'поисковая собака', 'search and rescue dog', 'rescue_ops'),
  ('іздеу-барлау жұмыстары', 'поисково-разведочные работы', 'exploration and prospecting operations', 'industrial_safety'),
  ('іздеу іс-шарасы', 'поисковое мероприятие', 'search operation / search activity', 'rescue_ops'),
  ('іздеуіш робот', 'поисковый робот', 'search and rescue robot', 'rescue_ops'),
  ('істердің толықтығы мен жай-күйін тексеру', 'проверка наличия и состояния дел', 'verification of the presence and condition of records', 'coordination'),
  ('ілгерілету', 'продвижение', 'promotion', 'coordination'),
  ('іс бойынша іс жүргізу', 'производство по делу', 'proceedings in the case / case proceedings', 'coordination'),
  ('ілінісу беріктігі', 'прочность сцепления', 'adhesion strength / bond strength', 'industrial_safety'),
  ('іске қосу / ұшыру', 'пуск / запуск', 'start / launch', 'industrial_safety'),
  ('іске қосу қондырғысы', 'пусковая установка', 'launcher', 'industrial_safety'),
  ('іске қосу кедергісі', 'пусковое сопротивление', 'starting resistance / starting resistor', 'industrial_safety'),
  ('іздестіру', 'розыск', 'search / manhunt / wanted notice', 'rescue_ops'),
  ('іздестіру шаралары', 'розыскные меры', 'investigative measures', 'rescue_ops'),
  ('ішкі бақылау жүйесі', 'система внутреннего контроля', 'internal control system', 'coordination'),
  ('із кесу', 'следопытство', 'tracking', 'rescue_ops'),
  ('ізкескіш', 'следоуказатель', 'track indicator', 'rescue_ops'),
  ('ішкі бақылау қызметі', 'служба внутреннего контроля', 'internal control function', 'coordination'),
  ('ізденуші', 'соискатель', 'applicant / jobseeker / candidate', 'coordination'),
  ('іргелес мемлекет', 'сопредельное государство', 'neighboring state', 'coordination'),
  ('ілеспе ведомость', 'сопроводительная ведомость', 'transmittal sheet / transmittal letter / accompanying sheet', 'coordination'),
  ('ілеспе жүкқұжат', 'сопроводительная накладная', 'waybill / consignment note / dispatch note', 'coordination'),
  ('ілеспе газдар', 'сопутствующие газы', 'associated gas / associated petroleum gas (APG)', 'industrial_safety'),
  ('ілініс', 'сцепление', 'clutch', 'industrial_safety'),
  ('іздеу кестесі', 'таблица поиска', 'lookup table', 'alerting_comms'),
  ('іштетілген трансформатор', 'трансформатор встроенный', 'built-in transformer / embedded transformer / bushing transformer', 'industrial_safety'),
  ('іссапар куәлігі', 'удостоверение командировочное', 'travel authorization / business trip certificate', 'coordination'),
  ('ілік', 'улика', 'evidence', 'coordination'),
  ('іс басқармасы', 'управление делами', 'administrative department / General Affairs Department', 'coordination'),
  ('іс басқарушы', 'управляющий делами', 'Chief Administrative Officer (CAO) / Head of Administration', 'coordination'),
  ('істердегі, құжаттардағы тізімдемелерді жетілдіру', 'усовершенствование описи дел, документов', 'improvement of the inventory of files and documents', 'coordination'),
  ('іске асыру деңгейі', 'уровень реализации', 'level of implementation', 'coordination'),
  ('істі қалыптастыру', 'формирование дела', 'compilation of the case file', 'coordination'),
  ('іргетас', 'фундамент', 'foundation', 'industrial_safety'),
  ('іргелі зерттеу', 'фундаментальное исследование', 'fundamental research', 'coordination'),
  ('ішінара іс-әрекетке қабілеттілік (нотариалдық қызмет)', 'частичная дееспособность', 'partial legal capacity / partial legal competence', 'coordination'),
  ('іс-қимыл жасау, жұмыс істеу, қызмет істеу', 'функционирование', 'functioning', 'coordination'),
  ('ішінара мамандану', 'частичная специализация', 'partial specialization', 'coordination'),
  ('ішінара тұрақтанған халық', 'частично стабильное население', 'partially stable population / partially stabilized population', 'coordination'),
  ('ішінара оқыту', 'частичное обучение', 'partial training', 'coordination'),
  ('істікше', 'штекер', 'plug / male connector / pin plug', 'alerting_comms'),
  ('ішкі энергия', 'энергия внутренняя', 'internal energy', 'industrial_safety'),
  ('іс жүргізудегі тіл саясаты', 'языковая политика в делопроизводстве', 'language policy in records management / office language policy', 'coordination')
;
