-- =============================================================
-- Restore: terms the user sent earlier that a later replacement by Kazakh
-- letter (Ж, С, К) removed because their Kazakh word starts with that letter
-- (5 from «А-41, Б-9»), and «көрсетілім — демонстрация» from «к-99», which
-- the import skipped. Every term from all the user's lists (0033–0051) that
-- is not on the site is added back; nothing else changes.
--
-- Applied with: npx supabase db query --linked -f supabase/migrations/0052_restore_user_terms.sql
-- =============================================================

begin;

insert into public.terms (kk, ru, en, category)
select f.kk, f.ru, f.en, f.cat from (values
('0033','өрт сөндіруші','пожарный','firefighter','fire_safety'),
('0033','өрт температурасы','температура пожара','fire temperature','fire_safety'),
('0033','өрт','пожар','fire, blaze','fire_safety'),
('0033','өрт ілмегі','багор пожарный','fire hook, pike pole','fire_safety'),
('0033','өрт кезінде адамдарды құлақтандыру және эвакуациялауды басқару жүйесі','система оповещения и управления эвакуацией людей при пожаре','public address and voice alarm','alerting_comms'),
('0033','өрт сөндіру-құтқару автомобилі','автомобиль пожарно-спасательный','rescue engine, firefighting appliance','fire_safety'),
('0033','өрт туралы акт','акт о пожаре','fire incident report','fire_safety'),
('0033','өрт сөндірушінің жауынгер киімі','боевая одежда пожарного','turnout gear','fire_safety'),
('0033','өрт сөндіргіш автомобильдің жауынгерлік тобы','боевой расчет пожарного автомобиля','fire company','fire_safety'),
('0033','өртпен күрес','борьба с пожарами','fire-fighting, fire control','fire_safety'),
('0033','өрт себепкері','виновник пожара','fire setter, incendiary','fire_safety'),
('0033','өрт сөндіру мүмкіндіктері','возможности по тушению пожара','fire-fighting capability, extinguishing capability','fire_safety'),
('0033','өрт жою уақыты','время ликвидации пожара','time of extinguishment','fire_safety'),
('0033','өрт тежеу уақыты','время локализации пожара','time of fire control','fire_safety'),
('0033','өрт оқшаулау уақыты','время локализации пожара','time of fire control','fire_safety'),
('0033','өртке жету уақыты','время следования на пожар','running time','fire_safety'),
('0033','өртте опат болу','гибель в огне','fire death, fire fatality','fire_safety'),
('0033','өрт сөндіру депосы','депо пожарное','fire station, fire house','fire_safety'),
('0033','өрт зардаптарын жою міндеттері','задачи по ликвидации последствий пожара','tasks for fire aftermath response','fire_safety'),
('0033','өртке ұқсату','имитация пожара','fire simulation','fire_safety'),
('0033','өрт қарқыны','интенсивность пожара','fire intensity','fire_safety'),
('0033','өрт сөндіргіш кеме','катер пожарный','fireboat','fire_safety'),
('0033','өрт сатысы','лестница пожарная','fire ladder','fire_safety'),
('0033','өрттің бастапқы өршу кезеңі','начальная стадия развития пожара','initial stage of fire development','fire_safety'),
('0033','өрт сөндіру бөлімінің бастығы','начальник пожарной части','fire station chief','fire_safety'),
('0033','өрт қауіпсіздігін қамтамасыз ету','обеспечение пожарной безопасности','fire-safety management','fire_safety'),
('0033','өрт басындағы жағдай','обстановка на месте пожара','fire scene conditions','fire_safety'),
('0033','өрт нысанасы','объект пожара','property involved, structure involved','fire_safety'),
('0033','өрттің қауіпті себептері','опасные факторы пожара','fire hazards','fire_safety'),
('0033','өрт сөндірудің шұғыл жоспары','оперативный план тушения пожара','firefighting operational plan','fire_safety'),
('0033','өрт шалған аумақ','площадь охваченная пожарами','fire-affected territory','fire_safety'),
('0033','өрт себебі','причина пожара','cause of fire, fire cause','fire_safety'),
('0033','өртенбейтін есік','противопожарная дверь','fire door','fire_safety'),
('0033','өртенбейтін жапқыш','противопожарная заслонка','fire damper','fire_safety'),
('0033','өртке қарсы қабырға','противопожарная стена','fire wall','fire_safety'),
('0033','өртке қарсы тосқауылдар','противопожарные преграды','fire breaks','fire_safety'),
('0033','өртке қарсы аралықтар','противопожарные разрывы','fire lines, fire breaks','fire_safety'),
('0033','өртке қарсы талаптар','противопожарные требования','fire protection requirements','fire_safety'),
('0033','өрт бөлімінің баратын ауданы','район выезда пожарной части','response district, first-due area','fire_safety'),
('0033','өртке қарсы тәртіп','режим противопожарный','fire safety regulations, fire prevention regime','fire_safety'),
('0033','өрт сөндіргіш жең','рукав пожарный','fire hose','fire_safety'),
('0033','өрт сөндіру басшысы','руководитель тушения пожара','incident commander','fire_safety'),
('0033','өзін-өзі жойғыш','самоликвидатор','self-destructor, self-destructive device','industrial_safety'),
('0033','өрттің өршу деңгейі','степень развития пожара','fire severity, stage of fire development','fire_safety'),
('0033','өртке қарсы қалқан','щит противопожарный','fire equipment board','fire_safety'),
('0033','өрт экспонометрі','экспонометр пожарный','exposure meter','fire_safety'),
('0033','өнеркәсіптік апат','промышленная катастрофа','industrial disaster','industrial_safety'),
('0033','өндірістік апат','авария производственная','industrial accident','industrial_safety'),
('0033','өндірістегі авария','авария производственная','industrial accident','industrial_safety'),
('0033','өртке қарсы бөгеуіл','барьер противопожарный','fire barrier','fire_safety'),
('0035','бұранда','винт','screw','industrial_safety'),
('0035','бастиек','головка','head','fire_safety'),
('0035','бықсып жану','горение затяжное','smouldering combustion','fire_safety'),
('0035','бықси жану','горение затяжное','smouldering combustion','fire_safety'),
('0035','барлау тобы','группа разведки','reconnaissance team','civil_defense'),
('0035','бөген','дамба','levee / dike','industrial_safety'),
('0035','біліктіліктен айыру','дисквалификация','disqualification','coordination'),
('0035','баянжазба','докладная (записка)','memorandum (memo)','coordination'),
('0035','баянхат','докладная записка','memorandum','coordination'),
('0035','бөгесін (уақытша істелген)','запруда','impound','industrial_safety'),
('0035','барлау аймағы','зона разведки','reconnaissance zone','civil_defense'),
('0035','біліктілік','квалификация','qualification','coordination'),
('0035','батальон командир','командир батальона','battalion commander','civil_defense'),
('0035','батарея командирі','командир батареи','battery commander','civil_defense'),
('0035','бөлімше командирі','командир отделения','squad leader','civil_defense'),
('0035','бүркемелеу','маскировка','camouflage','civil_defense'),
('0035','бүркемелеу іс-шаралары','маскировочные мероприятия','camouflage measures','civil_defense'),
('0035','бүркемелеу бөлімшелері','маскировочные подразделения','camouflage units','civil_defense'),
('0035','байқаушылық','наблюдаемость','observability','coordination'),
('0035','бейтараптану','нейтрализация','neutralization','industrial_safety'),
('0035','бейтараптандыру','нейтрализация','neutralization','industrial_safety'),
('0035','бөлімше','отделение','squad/ section','civil_defense'),
('0035','бөлік','отсек','compartment','industrial_safety'),
('0035','байланыс офицері','офицер связи','liaison officer','alerting_comms'),
('0035','беріліс функциясы','передаточная функция','transfer function','industrial_safety'),
('0035','бөгет','плотина','dam','industrial_safety'),
('0035','бақылау жолағы','полоса наблюдения','observation sector','civil_defense'),
('0035','бүркемелеу жолағы','полоса прикрытия','covering zone','civil_defense'),
('0035','барлау жолағы','полоса разведки','reconnaissance zone','civil_defense'),
('0035','бекет','пост','post','civil_defense'),
('0035','барлау авиациясы','разведывательная авиация','reconnaissance aviation / reconnaissance aircraft','civil_defense'),
('0035','барлау тобы','разведывательная группа','reconnaissance group','civil_defense'),
('0035','барлау-оқ ату кешені','разведывательно-огневой комплекс','reconnaissance and fire system','civil_defense'),
('0035','барлау-іздестіру тобы','разведывательно-поисковая группа','reconnaissance and search group','civil_defense'),
('0035','барлау деректері','разведывательные данные','intelligence data','civil_defense'),
('0035','барлау мәліметтері','разведывательные сведения','intelligence information / results of reconnaisance','civil_defense'),
('0035','барлау отряды','разведывательный отряд','reconnaissance detachment','civil_defense'),
('0035','баянат','рапорт','report','coordination'),
('0035','бедер','рельеф','terrain','civil_defense'),
('0035','байланысшы','связник','liaison officer','alerting_comms'),
('0035','бастапқы өрт сөндіру құралдары','средства первичного пожаротушения','portable fire-fighting equipment','fire_safety'),
('0035','бастау уақыты','стартовое время','start time','coordination'),
('0035','байланыс торабы','узел связи','communications center','alerting_comms'),
('0035','байрақ','штандарт','standard','civil_defense'),
('0035','биологиялық ластану','биологическое загрязнение','biological contamination','industrial_safety'),
('0035','браконьер','браконьер','poacher','industrial_safety'),
('0035','браконьерлік','браконьерство','poaching','industrial_safety'),
('0035','батпақтанғандық','заболоченность','wetland conditions','industrial_safety'),
('0035','бұташық','кустарничек','dwarf shrub','industrial_safety'),
('0035','бастапқы орман','лес первичный','primary forest','industrial_safety'),
('0035','бас арна','магистральный канал','main canal','industrial_safety'),
('0035','бұлтартпас дәлелдер','неопровержимые доказательства','conclusive evidence','coordination'),
('0035','бұрма арық','отводной арык','diversion canal','industrial_safety'),
('0035','биологиялық ыдырамайтын қалдықтар','отходы биологически неразложимые','non-biodegradable waste','industrial_safety'),
('0035','биологиялық ыдырайтын қалдықтар','отходы биологически разложимые','biodegradable waste','industrial_safety'),
('0035','биологиялық өнім','продукция биологическая','biological products','industrial_safety'),
('0035','бағалы тері кәсіпшілігі','промысел пушной','fur trapping; fur hunting','industrial_safety'),
('0035','балық кәсіпшілігі','промысел рыбный','fishing; commercial fishing','industrial_safety'),
('0035','биологиялық алуантүрлілік','разнообразие биологическое','biodiversity; biological diversity','industrial_safety'),
('0036','циклдік қозғалыс','движение циклическое','cyclic motion','industrial_safety'),
('0036','циркуляциялық су','вода циркуляционная','circulating water','industrial_safety'),
('0036','цилиндрлер бастиегі','головка цилиндров','cylinder head','industrial_safety'),
('0036','циркуляциялық арна','циркуляционный канал','circulation channel','industrial_safety'),
('0036','цистерна','цистерна','tank','industrial_safety'),
('0036','цифр','цифра','digit','coordination'),
('0036','цифрлық бейнеақпарат','цифровая видеоинформация','digital video information','alerting_comms'),
('0036','цифрлық навигациялық карта','цифровая навигационная карта','digital navigation map','coordination'),
('0036','ценоэкожүйе климаты','климат ценоэкосистемы','climate of the cenoecosystem','industrial_safety'),
('0036','цифрлық сигнал','цифровой сигнал','digital signal','alerting_comms'),
('0036','цифрлық түрлендіру','цифровые преобразования','digital transformations','alerting_comms'),
('0036','циркуляциялық сорғы','насос циркуляционный','circulation pump','industrial_safety'),
('0036','цифрлық мемлекетке өту','переход в цифровое государство','transition to a digital state','coordination'),
('0037','әкімшілік айыппұлдар','административные штрафы','administrative fines','coordination'),
('0037','әскери қабілеттілік','боевая способность','combat capability','civil_defense'),
('0037','әскери кеме','боевое судно','warship','civil_defense'),
('0037','әскерилендірілген құрылым','военизированное формирование','paramilitary formation','civil_defense'),
('0037','әскери әкімшілік','военная администрация','military administration','civil_defense'),
('0037','әскери академия','военная академия','military academy','civil_defense'),
('0037','әскери кафедра','военная кафедра','military department; military training department','civil_defense'),
('0037','әскери қуат','военная мощь','military power','civil_defense'),
('0037','әскери ғылым','военная наука','military science','civil_defense'),
('0037','әскери пошта','военная почта','military mail','civil_defense'),
('0037','әскери барлау','военная разведка','military intelligence','civil_defense'),
('0037','әскери стратегия','военная стратегия','military strategy','civil_defense'),
('0037','әскери құрылым','военная структура','military structure','civil_defense'),
('0037','әскери теория','военная теория','military theory','civil_defense'),
('0037','әскери терминология','военная терминология','military terminology','civil_defense'),
('0037','әскери техника','военная техника','military equipment','civil_defense'),
('0037','әскери топография','военная топография','military topography','civil_defense'),
('0037','әскери киім','военная форма','military uniform','civil_defense'),
('0037','әскери өнеркәсіп кешені','военно промышленный комплекс','military-industrial complex','civil_defense'),
('0037','әскери дәрігерлік комиссия','военно-врачебная комиссия','military medical commission','disaster_medicine'),
('0037','әскери-инженерлік іс','военно-инженерное дело','military engineering','civil_defense'),
('0037','әскери-инженерлік өнер','военно-инженерное искусство','military engineering; the art of military engineering','civil_defense'),
('0037','әскери-далалық госпиталь','военно-полевой госпиталь','field hospital','disaster_medicine'),
('0037','әскери-саяси стратегия','военно-политическая стратегия','military-political strategy','civil_defense'),
('0037','әскери-саяси блок','военно-политический блок','military-political bloc; military alliance','civil_defense'),
('0037','әскери-пошта қызметі','военно-почтовая служба','Military Postal Service','civil_defense'),
('0037','әскери-тергеу органдары','военно-следственные органы','military investigative bodies','civil_defense'),
('0037','әскери-қызметтік іс-қимыл','военно-служебная деятельность','military service activities','civil_defense'),
('0037','әскери-стратегиялық жағдайлар','военно-стратегические условия','military-strategic conditions','civil_defense'),
('0037','әскери-стратегиялық жоспар','военно-стратегический план','military strategic plan','civil_defense'),
('0037','әскери-стратегиялық плацдарм','военно-стратегический плацдарм','strategic bridgehead; strategic foothold','civil_defense'),
('0037','әскери-техникалық ынтымақтастық','военно-техническое сотрудничество','military-technical cooperation','civil_defense'),
('0037','әскери қызметші әйелдер','военнослужащие-женщины','servicewomen','civil_defense'),
('0037','әскери қызметші','военнослужащий','serviceman','civil_defense'),
('0037','әскери өкілдіктер','военные представительства','military representative offices','civil_defense'),
('0037','әскери кеңесші','военный советник','military adviser','civil_defense'),
('0037','әскери маман','военный специалист','military specialist','civil_defense'),
('0037','әскери трибунал','военный трибунал','military tribunal','civil_defense'),
('0037','әуе күштері','воздушные силы','air force','civil_defense'),
('0037','әскери тәртіп','воинская дисциплина','military discipline','civil_defense'),
('0037','әскери жарғылар','воинские уставы','military regulations','civil_defense'),
('0037','әскери полигон','воинский полигон','military training ground','civil_defense'),
('0037','әскери шен','воинский чин','military rank','civil_defense'),
('0037','әскери эшелон','воинский эшелон','military train','civil_defense'),
('0037','әскери тәрбие','воинское воспитание','military education; military upbringing','civil_defense'),
('0037','әскери атақ','воинское звание','military rank','civil_defense'),
('0037','әскер','войска','troops; military forces; armed forces','civil_defense'),
('0037','әскери тағылымдам','войсковая стажировка','military internship','civil_defense'),
('0037','әскери бөлім','войсковая часть','military unit','civil_defense'),
('0037','әскери бақылау','войсковое наблюдение','military observation','civil_defense'),
('0037','әскери құрама','войсковое соединение','military formation','civil_defense'),
('0037','әскери шаруашылық','войсковое хозяйство','military logistics','civil_defense'),
('0037','әлеуметтік оңалту','социальная реабилитация','social rehabilitation','disaster_medicine'),
('0037','әлеуметтік жағдай','социальное положение','social status','coordination'),
('0037','әлеуметтік қатер','социальный риск','social risk','coordination'),
('0037','әлеуметтік тәуекел','социальный риск','social risk','coordination'),
('0037','әскери топография','топография военная','military topography','civil_defense'),
('0037','әскери қауіпсіздік қатері','угроза военной безопасности','threat to military security','civil_defense'),
('0037','әскерлерді басқару','управление войсками','command and control of troops','civil_defense'),
('0038','чартер','чартер','charter','coordination'),
('0038','чартер-партия','чартер-партия','charter party','coordination'),
('0038','чартерлік рейс','чартерный рейс','charter flight','coordination'),
('0038','чартер, жалдау шарт','чартер','charter; charter agreement; charter contract','coordination'),
('0039','газбен өрт сөндірудің автоматты жүйесі','автоматическая система газового пожаротушения','automatic gas fire suppression system','fire_safety'),
('0039','газ-түтіннен қорғау қызметінің автомобилі','автомобиль газодымозащитной службы','gas and smoke protection service vehicle','fire_safety'),
('0039','газды шабуыл','газовая атака','gas attack','civil_defense'),
('0039','газ-түтіннен қорғау қызметі','газодымозащитная служба','gas and smoke protection service','fire_safety'),
('0039','галванилік элемент','гальванический элемент','galvanic cell','industrial_safety'),
('0039','гарнизондық қызмет','гарнизонная служба','garrison service','civil_defense'),
('0039','гарнизон жарғысы','гарнизонный устав','garrison regulations','civil_defense'),
('0039','генерал-полковник','генерал-полковник','Colonel General','civil_defense'),
('0039','гидравликалық жетек','гидравлический привод','hydraulic drive','industrial_safety'),
('0039','гидро қақпақша','гидроклапан','hydraulic valve','industrial_safety'),
('0039','гидроцилиндр','гидроцилиндр','hydraulic cylinder','industrial_safety'),
('0039','гильза, оққауыз','гильза','cartridge case','civil_defense'),
('0039','гуманитарлық көмек','гуманитарная помощь','humanitarian aid; humanitarian assistance','coordination'),
('0039','газсыздандыру пункті','дегазационный пункт','decontamination station','civil_defense'),
('0039','газсыздандыру','дегазация','decontamination','civil_defense'),
('0039','гарнизон бастығы','начальник гарнизона','garrison commander','civil_defense'),
('0039','газ-түтіннен қорғау қызметінің өрт сөндірушісі','пожарный газодымозащитной службы','gas and smoke protection firefighter','fire_safety'),
('0039','газтұтқы','противогаз','gas mask; ABC-protective mask','civil_defense'),
('0039','газтұмша','противогаз','gas mask; ABC-protective mask','civil_defense'),
('0039','географиялық ландшафт','географический ландшафт','geographical landscape','industrial_safety'),
('0039','газдануды бақылау','контроль загазованности','gas concentration monitoring','industrial_safety'),
('0039','газ шығындысы','выхлоп газа','gas exhaust; gas emission','industrial_safety'),
('0039','газ өткізгіш магистралі','газопровод магистральный','main gas pipeline; gas transmission pipeline','industrial_safety'),
('0039','гидрофобтандырғыш сұйықтық','жидкость гидрофобизирующая','hydrophobizing liquid','industrial_safety'),
('0039','гидратқа қарсы тежегіштер','антигидратные ингибиторы','antihydrate inhibitors','industrial_safety'),
('0039','газ тасымалдағыш','газ-носитель','carrier gas; gas carrier','industrial_safety'),
('0039','газ-күйе қоспасы','газо-сажевая смесь','gas-soot mixture','industrial_safety'),
('0039','газ фазасы','газовая фаза','gas phase','industrial_safety'),
('0039','газ кен орны','газовое месторождение','gas field','industrial_safety'),
('0039','газ режімі','газовый режим','gas regime','industrial_safety'),
('0039','газ конденсаттық кен орны','газоконденсатное месторождение','gas-condensate field','industrial_safety'),
('0039','газды қабаттар','газоносные пласты','gas-bearing strata','industrial_safety'),
('0039','газфазалық реакция','газофазная реакция','gas-phase reaction','industrial_safety'),
('0039','газфазалық термиялық үдеріс','газофазовый термический процесс','gas-phase thermal process','industrial_safety'),
('0039','газ сақтау бөлімі','газохранилище','gas storage facility','industrial_safety'),
('0039','геологиялық ерекшелік','геологическая особенность','geological feature','industrial_safety'),
('0039','геологиялық саты','геологическая ступень','geological stage','industrial_safety'),
('0039','геофизикалық жұмыстар','геофизические работы','geophysical operations','industrial_safety'),
('0039','геохимиялық жұмыстар','геохимические работы','geochemical operations','industrial_safety'),
('0039','гидраттық тығын','гидратная пробка','hydrate plug','industrial_safety'),
('0039','гидродинамикалық есептеулер','гидродинамические расчеты','hydrodynamic calculations','industrial_safety'),
('0039','гидрокарбонилдік кешендер','гидрокарбонильные комплексы','hydrocarbonyl complexes','industrial_safety'),
('0039','гидропероксидтер','гидропероксиды','hydroperoxides','industrial_safety'),
('0039','гумин қышқылы','гуминовая кислота','humic acid','industrial_safety'),
('0039','газ десорбциясы','десорбция газа','gas desorption','industrial_safety'),
('0039','газ қоры','запас газа','gas reserves','industrial_safety'),
('0039','геометриялық изомерлер','изомеры геометрические','geometric isomers','industrial_safety'),
('0039','газды құрғату','осушка газа','gas dehydration','industrial_safety'),
('0039','газ сынамасы','проба газа','gas sample','industrial_safety'),
('0039','газ тасымалы','транспорт газа','gas transportation','industrial_safety'),
('0039','газдандырғыш','газификатор','gasifier; gas generator','industrial_safety'),
('0039','геодезиялық негіз','геодезическая основа','geodetic framework','industrial_safety'),
('0039','гигроскопиялық ылғал','гигроскопическая влажность','hygroscopic moisture content','industrial_safety'),
('0039','гидротазалау','гидроочистка','hydrotreating','industrial_safety'),
('0039','гидроперфоратор','гидроперфоратор','hydraulic rock drill / hydraulic drill','industrial_safety'),
('0039','гидростаздық қысым','гидростатическое давление','hydrostatic pressure','industrial_safety'),
('0039','гидросоққылы бұрғылау','гидроударное бурение','hydraulic percussion drilling','industrial_safety'),
('0039','газ концентрациясы','концентрация газа','gas concentration','industrial_safety'),
('0039','газдың жылыстауы','миграция газа','gas migration','industrial_safety'),
('0039','гидрогеодинамикалық аномалия','аномалия гидрогеодинамическая','hydrogeodynamic anomaly','industrial_safety'),
('0039','гидрогеологиялық алап','бассейн гидрогеологический','hydrogeological basin','industrial_safety'),
('0039','геологиялық блок','блок геологический','geological block','industrial_safety'),
('0039','газқалпақ газы','газ газовых шапок','gas-cap gas','industrial_safety'),
('0039','газконденсат жатындар газы','газ газоконденсатных залежей','gas of gas-condensate deposits; gas in gas-condensate reservoirs','industrial_safety'),
('0039','газды гидраттар','газовые гидраты','gas hydrates','industrial_safety'),
('0040','пәрменді қауіпсіздік','безопасность активная','active safety','industrial_safety'),
('0040','персонал мен халықтың қауіпсіздігі','безопасность персонала и населения','personnel and public safety','civil_defense'),
('0040','психологиялық қауіпсіздік','безопасность психологическая','psychological safety','disaster_medicine'),
('0040','пайдаланылған газ','газ отработанный','exhaust gas','industrial_safety'),
('0040','парциалық қысым','давление парциальное','partial pressure','industrial_safety'),
('0040','пайдалану құжаттамасы','документация эксплуатационная','operational documentation','industrial_safety'),
('0040','пайдалы сыйымдылық','емкость полезная','useful capacity','industrial_safety'),
('0040','пәрмен','команда','command; team; crew','coordination'),
('0040','пойыз апаты','крушение поезда','train wreck; train accident','emergencies'),
('0040','пана','укрытие','shelter','civil_defense'),
('0040','пана','убежище','shelter; refuge','civil_defense'),
('0040','процесс, үдеріс','процесс','process','coordination'),
('0040','пост','пост','post','civil_defense'),
('0040','понтон паркі','понтонный парк','bridge train; pontoon park','rescue_ops'),
('0040','понтон көпір','понтонный мост','pontoon bridge','rescue_ops'),
('0040','понтон өткел','понтонная переправа','pontoon crossing','rescue_ops'),
('0040','патрульдеу','патрулирование','patrolling','civil_defense'),
('0041','алдыңғы топ','передовая группа','advance party','civil_defense'),
('0041','аванпост','аванпост','outpost','civil_defense'),
('0041','авариялық жағдай','аварийная обстановка','emergency situation / emergency conditions','emergencies'),
('0041','авариялық ахуал','аварийная обстановка','emergency situation / emergency conditions','emergencies'),
('0041','апатты жағдай','аварийная ситуация','emergency situation','emergencies'),
('0041','авариялық жағдай','аварийная ситуация','emergency situation','emergencies'),
('0041','апаттан құтқару жұмысы','аварийно-спасательная работа','emergency rescue operations','rescue_ops'),
('0041','авариялық-химиялық қауіпті заттек','аварийно-химически опасное вещество','hazardous chemical substance / hazardous chemical agent','industrial_safety'),
('0041','авариялық жөндеу','аварийный ремонт','emergency repair','industrial_safety'),
('0041','авария','авария','accident / incident','emergencies'),
('0041','авиалайнер','авиалайнер','airliner','civil_defense'),
('0041','авиатасымалдағыш','авианосец','aircraft carrier','civil_defense'),
('0041','авиациялық даярлық','авиационная подготовка','aviation training','civil_defense'),
('0041','авиациялық барлау','авиационная разведка','aerial reconnaissance','civil_defense'),
('0041','авиациялық қызмет','авиационная служба','aviation service','civil_defense'),
('0041','авиациялық бөлім','авиационная часть','aviation unit','civil_defense'),
('0041','авиациялық сүйемелдеу','авиационное сопровождение','air escort','civil_defense'),
('0041','авиациялық құрама','авиационное соединение','aviation formation','civil_defense'),
('0041','авиациялық корпус','авиационный корпус','air corps','civil_defense'),
('0041','авиациялық отряд','авиационный отряд','aviation detachment','civil_defense'),
('0041','авиациялық полигон','авиационный полигон','aviation range','civil_defense'),
('0041','авиация','авиация','aviation','civil_defense'),
('0041','автомеханикалық саты','автомеханическая лестница','aerial ladder truck','fire_safety'),
('0041','газ-түтіннен қорғау қызметінің автомобилі','автомобиль газодымозащитной службы','smoke and gas protection vehicle','fire_safety'),
('0041','жең төсегіш автомобилі','автомобиль для прокладки рукавов','hose-laying vehicle','fire_safety'),
('0041','жарық бергіш автомобиль','автомобиль освещения','lighting vehicle','fire_safety'),
('0041','өрт сөндіру-құтқару автомобилі','автомобиль пожарно-спасательный','fire and rescue vehicle','fire_safety'),
('0041','көбік-ұнтақпен өрт сөндіру автомобилі','автомобиль пожарный пенно-порошкового тушения','foam and dry-powder fire truck','fire_safety'),
('0041','жеңдік автомобиль','автомобиль рукавный','hose truck','fire_safety'),
('0041','жеңқұбырлы автомобиль','автомобиль рукавный','fire hose vehicle','fire_safety'),
('0041','байланыс қызметінің автомобилі','автомобиль службы связи','communications vehicle','alerting_comms'),
('0041','автосорғы','автонасос','fire pump vehicle','fire_safety'),
('0041','айдын','акватория','water area','rescue_ops'),
('0041','өрт туралы акт','акт о пожаре','fire report','fire_safety'),
('0041','жандандыру','активизация','activation','coordination'),
('0041','белсендіру','активизация','activation','coordination'),
('0041','радиоактив заттектің белсенділігі','активность радиоактивного вещества','radioactive material activity','civil_defense'),
('0041','альфа-сәулелендіру','альфа-излучение','alpha radiation','civil_defense'),
('0041','спектр талдағышы','анализатор спектра','spectrum analyzer','industrial_safety'),
('0041','аэростат','аэростат','aerostat','civil_defense'),
('0041','белтартпа','бандаж','reinforcing band','industrial_safety'),
('0041','бандаж','бандаж','reinforcing band / bandage (мед.)','disaster_medicine'),
('0041','деректер банкі','банк данных','data bank','coordination'),
('0041','байланыс батальоны','батальон связи','signal battalion','alerting_comms'),
('0041','жеңқұбырларды кептіруге арналған мұнара','башня для сушки рукавов','hose-drying tower','fire_safety'),
('0041','жең кептіргіш мұнара','башня для сушки рукавов','hose-drying tower','fire_safety'),
('0041','бета сәулелену','бета-излучение','beta radiation','civil_defense'),
('0041','бинарлы химиялық оқ-дәрі','бинарные химические боеприпасы','binary chemical munitions','civil_defense'),
('0041','биологиялық авария','биологическая авария','biological accident','emergencies'),
('0042','ювениль суы','воды ювениальные','juvenile waters','industrial_safety'),
('0042','заңдық құзыры','юрисдикция','jurisdiction','coordination'),
('0042','юриспруденция','юриспруденция','jurisprudence','coordination'),
('0044','радиоактив заттектің белсенділігі','активность радиоактивного вещества','activity of a radioactive substance','civil_defense'),
('0044','радиоактив элементтің белсенділігі','активность радиоактивного элемента','activity of a radioactive element','civil_defense'),
('0044','радиобелсенді атом','атом радиоактивный','radioactive atom','civil_defense'),
('0044','радиоактив заттек','вещество радиоактивное','radioactive substance; radioactive material','civil_defense'),
('0044','реттегіш','регулятор','regulator; control device','industrial_safety'),
('0044','режим, тәртіп','режим','regime','coordination'),
('0044','реакция','реакция','reaction','industrial_safety'),
('0044','резус-фактор','резус-фактор','Rh factor','disaster_medicine'),
('0044','радиактивті ластану','радиоактивное загрязнение','radioactive contamination','civil_defense'),
('0044','рельстің істен шығуы','выход рельсов из строя','rail failure','industrial_safety'),
('0044','разрядты жүк','груз разрядный','special-category dangerous cargo','industrial_safety'),
('0044','реверсивті қозғалыс','движение реверсивное','reversible traffic / bidirectional traffic','industrial_safety'),
('0044','рельс жымының алға шығуы','забегание рельсовых стыков','rail joint stagger','industrial_safety'),
('0044','рельстер арасындағы саңылау','зазор между рельсами','rail gap; rail joint gap','industrial_safety'),
('0044','радио байланыс арнасы','канал радиосвязи','radio communication channel','alerting_comms'),
('0044','рельстің омырылуы','излом рельса','rail fracture','industrial_safety'),
('0044','рельстің тозуы','износ рельса','rail wear','industrial_safety'),
('0044','реттегіш сына','клин регулировочный','adjustment wedge','industrial_safety'),
('0044','рельсті сынау','испытание рельса','rail testing','industrial_safety'),
('0044','реостат','реостат','rheostat','industrial_safety'),
('0044','реагенттер','реагенты','reagent','industrial_safety'),
('0045','улы заттек','вещество ядовитое','poisonous substance; toxic substance','industrial_safety'),
('0045','ультрадыбыстық толқындар','волны ультразвуковые','ultrasonic waves','industrial_safety'),
('0045','ультрақысқа толқындар','волны ультракороткие','ultrashort waves','alerting_comms'),
('0045','уақытша бос мемлекеттік лауазым','временная вакансия на государственную должность','temporary vacancy for a civil service position','coordination'),
('0045','уақытша қорғау визасы','временная защитная виза','temporary protective visa','coordination'),
('0045','уақытша еңбекке жарамсыздық','временная нетрудоспособность','temporary incapacity for work; temporary disability','disaster_medicine'),
('0045','уақытша сақтау','временное хранение','temporary storage','industrial_safety'),
('0045','уытсыздандыру','детоксикация','detoxification','disaster_medicine'),
('0045','уақытша жол','дорога временная','temporary road','industrial_safety'),
('0045','уату','дробление','crushing','industrial_safety'),
('0045','уақытша белгі','знак временный','temporary sign','industrial_safety'),
('0045','ультракүлгін сәулелендіру','излучение ультрафиолетовое','ultraviolet radiation','industrial_safety'),
('0045','уақытша ұстау изоляторы','изолятор временного содержания','temporary detention center','coordination'),
('0045','улану','интоксикация','intoxication','disaster_medicine'),
('0045','уақыт сызығы','линия времени','timeline','coordination'),
('0045','усойқы майлар','масла сивушные','fusel oils','industrial_safety'),
('0045','уәждеме','мотивация','motivation','coordination'),
('0045','уран тотығы','окись урана','uranium oxide','industrial_safety'),
('0045','ушыққан аурулар','острые заболевания','acute diseases','disaster_medicine'),
('0045','уытты қалдықтар','отходы токсичные','toxic waste','industrial_safety'),
('0045','улы қалдықтар','отходы ядовитые','poisonous waste','industrial_safety'),
('0045','уақыт тұрақтысы','постоянная времени','time constant','coordination'),
('0045','уәкілетті өкіл','представитель уполномочный','authorized representative','coordination'),
('0045','уқайтарғыштар','противоядия','antidotes','disaster_medicine'),
('0045','уытты доза','токсическая доза','toxic dose','disaster_medicine'),
('0045','уытты араласпа','токсичные примеси','toxic impurities','industrial_safety'),
('0045','ультиматум','ультиматум','ultimatum','coordination'),
('0045','уәкілетті мемлекеттік орган','уполномоченный государственный орган','authorized state body','coordination'),
('0045','уәкілеттік беру','уполномочивать','authorize','coordination'),
('0045','уақытша орналастыру орталығы','центр временного размещения','temporary accommodation center','evacuation'),
('0045','ушығу','эскалация','escalation','coordination'),
('0045','улы газ','ядовитый газ','poisonous gas','civil_defense'),
('0045','уландырғыш заттек','вещество отравляющее','poisonous substance','civil_defense'),
('0045','учәскелік дәрігер, учәске дәрігері','врач участковый','district physician','disaster_medicine'),
('0045','уақытша бақылау пункті','временный контрольный пункт','temporary checkpoint','civil_defense'),
('0045','уақыт интервалы','временной интервал','time interval','coordination'),
('0045','уақытша шекаралық бекет','временный пограничный пост','temporary border post','civil_defense'),
('0045','уәж','мотив','motive','coordination'),
('0045','учаске','участок','section','coordination'),
('0046','вакуумды сүзгі','вакуум-фильтр','vacuum filter','industrial_safety'),
('0046','вагонды ашу актісі','акт вскрытия вагона','Railcar Opening Report','industrial_safety'),
('0046','вагон','вагон','railcar','industrial_safety'),
('0046','вакуум','вакуум','vacuum','industrial_safety'),
('0046','вакуумөлшеуіш','вакуумметр','vacuum gauge','industrial_safety'),
('0046','вариант, нұсқа','вариант','variant','coordination'),
('0046','вариатор','вариатор','variable-speed drive','industrial_safety'),
('0046','вагонды желдету','вентиляция вагона','railcar ventilation','industrial_safety'),
('0046','вентури түтігі','вентури-трубка','venturi tube','industrial_safety'),
('0046','вагондарды таразылау','взвешивание вагонов','railcar weighing','industrial_safety'),
('0046','вокзал','вокзал','railway station','industrial_safety'),
('0046','вольтметр','вольтметр','voltmeter','industrial_safety'),
('0046','вольфрам','вольфрам','tungsten','industrial_safety'),
('0046','вулкандау','вулканизация','vulcanisation','industrial_safety'),
('0046','вагонның істен шығуы','выход вагонов из строя','railcar failures','industrial_safety'),
('0046','вагонның жүккөтерімділігі','грузоподъемность вагона','railcar load capacity','industrial_safety'),
('0046','вагондар тобы','группа вагонов','group of railcars','industrial_safety'),
('0046','вагон топтастыру','группировка вагонов','grouping of railcars','industrial_safety'),
('0046','вагонды газсыздандыру','дегазация вагонов','railcar degassing','industrial_safety'),
('0046','вагонды зарарсыздандыру','дезинфекция вагона','railcar disinfection','industrial_safety'),
('0046','вагон депосы','депо вагонов','railcar depot','industrial_safety'),
('0046','вагон жөндеу депосы','депо вагоноремонтное','railcar repair depot','industrial_safety'),
('0046','вагон ұзындығы','длина вагона','railcar length','industrial_safety'),
('0046','виртуал ұзынды','длина виртуальная','virtual length','coordination'),
('0046','вагон домкраты','домкрат вагонный','railcar jack','industrial_safety'),
('0046','вагон жөндеу зауыты','завод вагоноремонтный','railcar repair plant','industrial_safety'),
('0046','вагондарды бекіту','закрепление вагонов','securing of railcars','industrial_safety'),
('0046','вагон баяулатқысы','замедлитель вагонный','railcar retarder','industrial_safety'),
('0046','вагондар қоры','запас вагонов','railcar reserve','industrial_safety'),
('0046','вагон арқалығының омырылымы','излом балки вагона','fracture of a railcar beam','industrial_safety'),
('0046','вагон білігінің омырылымы','излом вала вагона','railcar axle shaft fracture','industrial_safety'),
('0046','вагондарды оқшаулау','изоляция вагонов','railcar insulation','industrial_safety'),
('0046','вагон санаты','категория вагона','railcar category','industrial_safety'),
('0046','вагонның жүріс сапасы','качество вагона ходовое','railcar running performance','industrial_safety'),
('0046','вагон тербелісі','колебание вагона','railcar oscillation','industrial_safety'),
('0046','вагон доңғалағы','колесо вагона','railcar wheel','industrial_safety'),
('0046','вибрациялық конвейер','конвейер вибрационный','vibrating conveyor','industrial_safety'),
('0046','вагон шанағы','кузов вагона','railcar body','industrial_safety'),
('0046','ваготомия','ваготомия','vagotomy','disaster_medicine'),
('0046','вариациялық қатар','вариационный ряд','variation series','coordination'),
('0046','вируленттік','вирулентность','virulence','disaster_medicine'),
('0046','вольер','вольер','enclosure','industrial_safety'),
('0046','вакуумдық бекітпе','вакуумный затвор','vacuum valve','industrial_safety'),
('0046','видеокард','видеокарта','graphics card','coordination'),
('0046','видеожады','видеопамять','video memory','coordination'),
('0046','вибрация, діріл','вибрация','vibration','industrial_safety'),
('0046','винт','винт','screw','industrial_safety'),
('0046','вакуум-сорғы','вакуум-насос','vacuum pump','industrial_safety'),
('0046','вентиль','вентиль','valve','industrial_safety'),
('0046','взвод командирі','командир взвода','platoon commander','civil_defense'),
('0046','веб-браузер','веб-браузер','web browser','coordination'),
('0046','веб-дизайн','веб-дизайн','web design','coordination'),
('0046','веб-сервер','веб-сервер','web server','coordination'),
('0046','векторлық график','векторная графика','vector graphics','coordination'),
('0046','виртуал мәшине','виртуальная машина','virtual machine','coordination'),
('0046','вазоконстрикция','вазоконстрикция','vasoconstriction','disaster_medicine'),
('0046','ваксиналау','вакцинация','vaccination','disaster_medicine'),
('0046','вегетациялық кезең','вегетационный период','growing season','industrial_safety'),
('0047','ғарыш сәулесі','космические лучи','cosmic rays','industrial_safety'),
('0047','ғимараттың ұзаққа төзімділігі','долговечность зданий','building durability','industrial_safety'),
('0047','ғылымға қайшы','антинаучный','unscientific','coordination'),
('0047','ғаныш','ганч','gypsum plaster','industrial_safety'),
('0047','ғаныш','гипс','gypsum','industrial_safety'),
('0047','ғарыштық түсірімдерді айқындау','дешифрирование космических снимков','interpretation of satellite imagery','coordination'),
('0047','ғылым докторы','доктор наук','doctor of science','coordination'),
('0047','ғылыми-техникалық құжаттама','документация научно-техническая','scientific and technical documentation','coordination'),
('0047','ғимарат','здание','building','industrial_safety'),
('0047','ғимараттар мен құрылыстар; ғимараттар мен құрылысжайлар','здания и сооружения','buildings and structures','industrial_safety'),
('0047','ғарыштық сәулелендіру','излучение космическое','cosmic radiation','industrial_safety'),
('0047','ғылыми-зерттеу институты','институт научно-исследовательский','research institute','coordination'),
('0047','ғимараттар арасындағы кәбіл','кабель между зданиями','interbuilding cable','industrial_safety'),
('0047','ғылым кандидаты','кандидат наук','candidate of sciences','coordination'),
('0047','ғарыш кемесі','корабль космический','spacecraft','coordination'),
('0047','ғимарат дәлізі','коридор здания','building corridor','industrial_safety'),
('0047','ғарыш қызметі','космическая деятельность','space activities','coordination'),
('0047','ғарыштық байланыс','космическая связь','space communications','alerting_comms'),
('0047','ғарыштық жылдамдық','космическая скорость','cosmic velocity','coordination'),
('0047','ғарыштық орта','космическая среда','space environment','coordination'),
('0047','ғарыш аппараты','космический аппарат','spacecraft','coordination'),
('0047','ғарыш мазері','космический мазер','space maser','coordination'),
('0047','ғарыш объектісі','космический объект','space object','coordination'),
('0047','ғарыштық ұшу','космический полет','space flight','coordination'),
('0047','ғарыштық сәуле әсері','космическое излучение','cosmic radiation','industrial_safety'),
('0047','ғарыш кеңістігі','космическое пространство','outer space','coordination'),
('0047','ғаламнама','космогония','cosmogony','coordination'),
('0047','ғарыш айлағы','космодром','spaceport','coordination'),
('0047','ғарыштану','космология','cosmology','coordination'),
('0047','ғарышкер','космонавт','cosmonaut','coordination'),
('0047','ғарышнама','космонавтика','astronautics','coordination'),
('0047','ғарыш','космос','space','coordination'),
('0047','ғарышхимия','космохимия','cosmochemistry','coordination'),
('0047','ғарыштық байланыс желісі','линия космической связи','space communication link','alerting_comms'),
('0047','ғашықтық эпос','любовный эпос','romantic epic','coordination'),
('0047','ғұмырнама','мемуар','memoir','coordination'),
('0047','ғұлама','мудрец','sage','coordination'),
('0047','ғарыш аппараттарын жерүсті басқару кешені','наземный комплекс управления космических аппаратов','ground-based spacecraft control complex','coordination'),
('0047','ғылым','наука','science','coordination'),
('0047','ғылымтану','науковедение','science studies','coordination'),
('0047','ғылымды қажетсінетін салалар','наукоемкие отрасли','high-tech industries','coordination'),
('0047','ғылымды қажетсінетін өндіріс','наукоемкое производство','high-tech manufacturing','coordination'),
('0047','ғылымды қажетсінушілік','наукоемкость','knowledge intensity','coordination'),
('0047','ғылыми қамтымдық','наукоемкость','knowledge intensity','coordination'),
('0047','ғылыми қызмет','научная деятельность','scientific activity','coordination'),
('0047','ғылыми жазба','научная запись (отчет)','scientific report','coordination'),
('0047','ғылыми зияткерлік меншік','научная интеллектуальная собственность','scientific intellectual property','coordination'),
('0047','ғылыми инфрақұрылым','научная инфраструктура','research infrastructure','coordination'),
('0047','ғылыми мақала','научная статья','scientific article','coordination'),
('0047','ғылыми фантастика','научная фантастика','science fiction','coordination'),
('0047','ғылыми-зерттеу жұмысы','научно-исследовательская работа','research work','coordination'),
('0047','ғылыми-әдістемелік жұмыс','научно-методическая работа','scientific and methodological work','coordination'),
('0047','ғылыми-көпшілік мақала','научно-популярная статья','popular science article','coordination'),
('0047','ғылыми-анықтамалық аппарат','научно-справочный аппарат','scholarly reference apparatus','coordination'),
('0047','ғылыми-техникалық қызмет','научно-техническая деятельность','scientific and technical activities','coordination'),
('0047','ғылыми-техникалық ақпарат','научно-техническая информация','scientific and technical information','coordination'),
('0047','ғылыми-техникалық төңкеріс','научно-техническая революция','scientific and technological revolution','coordination'),
('0047','ғылыми-техникалық құралдар','научно-технические средства','scientific and technical equipment','coordination'),
('0047','ғылыми фантастикалық әдебиет','научно-фантастическая литература','science fiction literature','coordination'),
('0047','ғылыми-фантастикалық жанр','научно-фантастический жанр','science fiction genre','coordination'),
('0047','ғылыми басылым','научное издание','scientific publication','coordination'),
('0047','ғылыми зерттеу','научное исследование','scientific research','coordination'),
('0047','ғылыми құқықтық сана','научное правосознание','scientific legal consciousness','coordination'),
('0047','ғылыми баяндама','научный доклад','scientific report','coordination'),
('0047','ғылыми стиль','научный стиль','scientific style','coordination'),
('0047','ғылым қажеттілігі','необходимость науки','the need for science','coordination'),
('0047','ғұрып','обычай','custom','coordination'),
('0047','ғаламшар','планета','planet','coordination'),
('0047','ғарышкердің құқықтық жағдайы','правовое положение космонавта','legal status of a cosmonaut','coordination'),
('0047','ғылыми жетекші','руководитель научный','scientific supervisor','coordination'),
('0047','ғарыш аппаратын құрастыру','сборка космического аппарата','spacecraft assembly','coordination'),
('0047','ғылыми еңбектер жинағы','сборник научных трудов','collection of scientific papers','coordination'),
('0047','ғаламдық желі','сеть глобальная','global network','alerting_comms'),
('0047','ғалымдар кеңесі','совет ученых','council of scientists','coordination'),
('0047','ғарыш аппараттарын сүйемелдеу','сопровождение космических аппаратов','spacecraft support','coordination'),
('0047','ғылыми қызметкер','сотрудник научный','research scientist','coordination'),
('0047','ғарыштық тәуекелдіктерді сақтандыру','страхование космических рисков','space risk insurance','coordination'),
('0047','ғарыштық байланыс телепорты','телепорт космической связи','space communications teleport','alerting_comms'),
('0047','ғарыш аппараттары үшін тоқтап тұру нүктесі; ғарыш аппараттарына арналған тұру нүктесі','точка стояния для космических аппаратов','orbital position for spacecraft','coordination'),
('0047','ғалым','ученый','scientist','coordination'),
('0047','ғалым хатшы','ученый секретарь','scientific secretary','coordination'),
('0047','ғылыми кеңес','ученый совет','academic council','coordination'),
('0048','жемірілу','абразия','abrasion','industrial_safety'),
('0048','жерасты құрылысындағы авария','авария на подземном сооружении','accident at an underground facility','emergencies'),
('0048','жанармай құю','автозаправка','filling station','industrial_safety'),
('0048','желіні қорғау автоматы','автомат для защиты сети','circuit breaker','alerting_comms'),
('0048','жоғарғы сыныпты автомобиль','автомобиль высшего класса','luxury car','industrial_safety'),
('0048','жүк автомобилі','автомобиль грузовой','truck','industrial_safety'),
('0048','жең төсегіш автомобилі','автомобиль для прокладки рукавов','hose-laying vehicle','fire_safety'),
('0048','жеңқұбырлар салуға арналған автомобиль','автомобиль для прокладки рукавов','hose-laying vehicle','fire_safety'),
('0048','жабық автомобиль','автомобиль закрытый','enclosed vehicle','industrial_safety'),
('0048','жеңіл автомобиль','автомобиль легковой','passenger car','industrial_safety'),
('0048','жарық бергіш автомобиль','автомобиль освещения','lighting vehicle','fire_safety'),
('0048','жеңқұбырлы автомобиль','автомобиль рукавный','hose tender','fire_safety'),
('0048','жеңдік автомобиль','автомобиль рукавный','hose tender','fire_safety'),
('0048','жол талғамайтын автомобиль','автомобиль-вездеход','cross-country vehicle','fire_safety'),
('0048','жемірлік','агрессивность (хим.)','corrosivity','industrial_safety'),
('0048','жандандыру','активация','activation','industrial_safety'),
('0048','жедел ақпаратты талдау','анализ оперативной информации','analysis of operational information','coordination'),
('0048','жол дәріқобдиша','аптечка дорожная','vehicle first aid kit','disaster_medicine'),
('0048','жаңбырға қарсы бөгеуіл','барьер противодождевой','rain barrier','industrial_safety'),
('0048','жерасты суы алабы','бассейн подземных вод','groundwater basin','industrial_safety'),
('0048','жол қозғалыс қауіпсіздігі','безопасность дорожного движения','road traffic safety','industrial_safety'),
('0048','жеңіл бетон','бетон легкий','lightweight concrete','industrial_safety'),
('0048','жертөле','блиндаж','dugout','civil_defense'),
('0048','жауынгерлік мүмкіндік','боевая возможность','combat capability','civil_defense'),
('0048','жауынгерлік машық','боевая выучка','combat proficiency','civil_defense'),
('0048','жауынгерлік іс-қимыл','боевая деятельность','combat operations','civil_defense'),
('0048','жауынгерлік бірлік','боевая единица','combat unit','civil_defense'),
('0048','жауынгерлік тапсырма','боевая задача','combat mission','civil_defense'),
('0048','жауынгерлік қызмет','боевая служба','combat duty','civil_defense'),
('0048','жауынгерлік тиімділік','боевая эффективность','combat effectiveness','civil_defense'),
('0048','жауынгерлік кезекшілік','боевое дежурство','combat duty','civil_defense'),
('0048','жауынгерлік ту','боевое знамя','battle flag','civil_defense'),
('0048','жауынгерлік қамтамасыз ету','боевое обеспечение','combat support','civil_defense'),
('0048','жауынгерлік өрістету','боевое развертывание','combat deployment','civil_defense'),
('0048','жауынгерлік тәжірибе','боевой опыт','combat experience','civil_defense'),
('0048','жауынгерлік бұйрық','боевой приказ','combat order','civil_defense'),
('0048','жауынгерлік атқыштоп','боевой расчет','combat crew','civil_defense'),
('0048','жауынгерлік құрам','боевой состав','combat strength','civil_defense'),
('0048','жауынгерлік жарғы','боевой устав','combat manual','civil_defense'),
('0048','жұқпалы аурулар','болезни инфекционные','infectious diseases','disaster_medicine'),
('0048','жал','вал','shaft','industrial_safety'),
('0048','желдету','вентиляция','ventilation','industrial_safety'),
('0048','жедел болжам','версия оперативная','working hypothesis','coordination'),
('0048','жылулық жарылыс','взрыв тепловой','thermal explosion','industrial_safety'),
('0048','жару','взрывание','explosion','industrial_safety'),
('0048','жарғыш','взрыватель','fuze','civil_defense'),
('0048','жарылыс толқыны','взрывная волна','blast wave','industrial_safety'),
('0048','жаратын декомпрессия','взрывная декомпрессия','explosive decompression','industrial_safety'),
('0048','жарылыс жарақаты','взрывная травма','blast injury','disaster_medicine'),
('0048','жарылыс жұмыстары','взрывные работы','blasting operations','industrial_safety'),
('0048','жарылыс құрылғылары','взрывные устройства','explosive devices','industrial_safety'),
('0048','жарылыс қауіпсіздігі','взрывобезопасность','explosion safety','industrial_safety'),
('0048','жарылыстан қорғау','взрывозащищенность','explosion protection','industrial_safety'),
('0048','жарылыс қаупі бар қоспа','взрывоопасная смесь','explosive mixture','industrial_safety'),
('0048','жарылу қаупі','взрывоопасность','explosion hazard','industrial_safety'),
('0048','жарылыс қауіпті','взрывоопасный','explosive','industrial_safety'),
('0048','жарылу-өртену қаупі бар заттек','взрывопожарное вещество','fire- and explosion-hazardous substance','fire_safety'),
('0048','жарылыс-техникалық топ','взрывотехническая группа','Explosive Ordnance Disposal (EOD) Team','civil_defense'),
('0048','жарылысты техникалық жұмыстар','взрывотехнические работы','explosive ordnance disposal (EOD) operations','civil_defense'),
('0048','жарылыс-техникалық зерттеу','взрывотехническое исследование','explosive ordnance examination','civil_defense'),
('0048','жарылысқа төзімділік','взрывоустойчивость','blast resistance','industrial_safety'),
('0048','жарылғыш қасиеті','взрывчатые свойства','explosive properties','industrial_safety'),
('0048','жазалау; өндіріп алу','взыскание','penalty','civil_defense'),
('0048','жылжымалы бастоған','водозабор передвижной','mobile water intake','fire_safety'),
('0048','жауынгер','воин','serviceman','civil_defense'),
('0048','жауынгерлік айбын','воинская доблесть','military valor','civil_defense'),
('0048','жауынгерлік абырой','воинская честь','military honour','civil_defense'),
('0048','жауынгерлік','воинский','military','civil_defense'),
('0048','жанартау','вулкан','volcano','emergencies'),
('0048','жанартаулық жер сілкінісі','вулканическое землетрясение','volcanic earthquake','emergencies'),
('0048','жанартау атқылауы','вулканическое извержение','volcanic eruption','emergencies'),
('0048','желдету','выветривание','weathering','industrial_safety'),
('0048','жанып кету','выгорать','burn out','fire_safety'),
('0048','жылжымалы өрт сөндіру сатысы','выдвижная пожарная лестница','extension fire ladder','fire_safety'),
('0048','жылу бөліну','выделение тепла','heat release','industrial_safety'),
('0048','жоғары температурада қайнайтын органикалық заттектер','высококипящие органические вещества','high-boiling organic substances','industrial_safety'),
('0048','жоғары температурада қайнайтын қалдықтар','высококипящие остатки','high-boiling residues','industrial_safety'),
('0048','жоғары күкіртті газ','высокосернистый газ','high-sulfur gas','industrial_safety'),
('0048','жоғары температуралы аймақ','высокотемпературная зона','high-temperature zone','industrial_safety'),
('0048','жоғары жиілікті қондырғы','высокочастотная установка','high-frequency installation','industrial_safety'),
('0048','жүк көтеру биіктігі','высота подъема груза','load lifting height','industrial_safety'),
('0048','жоғарғы көрсеткіш','высший показатель','highest indicator','coordination'),
('0048','жандандыру, серпіліс беру','генерировать','generate','coordination'),
('0048','жер сілкінісі гипосентрі','гипоцентр землетрясения','earthquake hypocenter','emergencies'),
('0048','жаһандану','глобализация','globalisation','coordination'),
('0048','жаһандық ластану','глобальное загрязнение','global pollution','industrial_safety'),
('0048','жану','горение','combustion','fire_safety'),
('0048','жанғыштық','горючесть','flammability','fire_safety'),
('0048','жанғыш газдар','горючие газы','flammable gases','fire_safety'),
('0048','жанғыш пайдалы қазбалар','горючие полезные ископаемые','combustible minerals','industrial_safety'),
('0048','жедел желі','горячая линия','hotline','coordination'),
('0048','жүк','груз','load','industrial_safety'),
('0048','жүк мәшинесі','грузовик','truck','industrial_safety'),
('0048','жолдың жүктасымалдылығы','грузонапряженность дороги','traffic load','industrial_safety'),
('0048','жүк тасымалы','грузоперевозки','freight transportation','industrial_safety'),
('0048','жүк тасқыны','грузопоток','freight flow','industrial_safety'),
('0048','жедел жауынгерлік қалқалау тобы','группа оперативно-боевого прикрытия','operational combat support team','civil_defense'),
('0048','жедел сарапшылық қолдау және ынтымақтастық тобы','группа оперативной экспертной поддержки и сотрудничества','Operational Expert Support and Cooperation Group','coordination'),
('0048','жоғары деңгейдегі жоспарлау тобы','группа планирования высокого уровня (гпву)','High-Level Planning Group (HLPG)','coordination'),
('0048','жұмысшы топ','группа рабочая','working group','coordination'),
('0048','жауынгерлік резерв тобы','группа резерва боевого','combat reserve group','civil_defense'),
('0048','жанасу датчигі','датчик касания','touch sensor','alerting_comms'),
('0048','жоғары айналымды қозғалтқыш','двигатель высокооборотный','high-speed engine','industrial_safety'),
('0048','жылулық қозғалтқыш','двигатель тепловой','heat engine','industrial_safety'),
('0048','жергілікті жол қозғалысы','движение дорожное местное','local road traffic','industrial_safety'),
('0048','жылулық қозғалыс','движение тепловое','thermal motion','industrial_safety'),
('0048','жарылыс','детонация','detonation','industrial_safety'),
('0048','жол ұзындығы','длина пути','path length','industrial_safety'),
('0048','жас өрт сөндірушілер жасағы','дружина юных пожарных','Young Firefighters'' Brigade','fire_safety'),
('0048','жеңқұбыр қысқышы','зажим рукавный','fire hose clamp','fire_safety'),
('0048','жерге тұйықтау','заземление','earthing / grounding','industrial_safety'),
('0048','жанғыш газ қорлары','запасы горючих газов','stocks of flammable gases','industrial_safety'),
('0048','жергілікті жердің зақымдануы','заражение местности','contamination of the area','civil_defense'),
('0048','жобадан тыс авария','запроектная авария','beyond-design-basis accident (BDBA)','emergencies'),
('0048','жемірілулік қорғаныс','защита от коррозии','corrosion protection','industrial_safety'),
('0048','жер сілкінісі','землетрясение','earthquake','emergencies'),
('0049','спринклерлік өрт сөндірудің автоматты жүйесі','автоматическая система спринклерного пожаротушения','automatic fire sprinkler system','fire_safety'),
('0049','санитариялық авиация','авиация санитарная','aeromedical evacuation','disaster_medicine'),
('0049','сіңіру','абсорбировать','to absorb','industrial_safety'),
('0049','сол рөлді автомобиль','автомобиль леворульный','left-hand drive (LHD) vehicle','industrial_safety'),
('0049','сейсмикалық режім аномалиясы','аномалия сейсмического режима','seismic regime anomaly','emergencies'),
('0049','сейсмикаға қарсы белдеу','антисейсмический пояс','seismic belt','emergencies'),
('0049','сегізкөздік анестезия','анестезия сакральная','sacral anesthesia','disaster_medicine'),
('0049','селқостық','апатичность, апатия','apathy, listlessness','disaster_medicine'),
('0049','соқырішектің жарылуы','аппендицит перфоративный','perforated appendicitis','disaster_medicine'),
('0049','сағалық арматура','арматура устья (устьевая арматура скважины)','wellhead equipment','industrial_safety'),
('0049','сұйықтық','жидкость','liquid, fluid','industrial_safety'),
('0049','сауал','запрос','request, inquiry','coordination'),
('0049','сұрау салу','запрос','request, inquiry','coordination'),
('0049','сырық - саты','лестница-палка','pole ladder','fire_safety'),
('0049','сорғы','насос','pump','fire_safety'),
('0049','саптық-өрт сөндіру дайындығы','пожарно-строевая подготовка','firefighter drill and training','fire_safety'),
('0049','сақтандырғыш ысырма','предохранительная задвижка','safety valve','fire_safety'),
('0049','сорғыш жең','рукав всасывающий','suction hose','fire_safety'),
('0049','сигналдау','сигнализация','alarm system','alerting_comms'),
('0049','ситуация, жағдай','ситуация','situation','coordination'),
('0049','стандарт','стандарт','standard','coordination'),
('0049','сұлба','схема','scheme','coordination'),
('0049','сүзгілеу стансасы','фильтровальная станция','water filtration plant','industrial_safety'),
('0049','сарапшы','эксперт','expert','coordination'),
('0049','сулы эмульсия','водная эмульсия','aqueous emulsion','industrial_safety'),
('0049','сулы-күйелік суспензия','водно-сажевая суспензия','carbon black-water suspension','industrial_safety'),
('0049','суда еритін тежегіштер','водорастворимые ингибиторы','water-soluble corrosion inhibitors','industrial_safety'),
('0049','су буы','водяной пар','water vapor, steam','industrial_safety'),
('0049','сыртқы диффузия','внешняя диффузия','external diffusion','industrial_safety'),
('0049','сұйық сіңіргіш','жидкий поглотитель','liquid absorber, liquid absorbent','industrial_safety'),
('0049','сәулелі энергия','лучистая энергия','radiant energy','industrial_safety'),
('0049','сәуле шығару қабілеті','лучеиспускательная способность','emissive power, emissivity','industrial_safety'),
('0049','салыстырмалы тығыздық','относительная плотность','specific gravity, relative density','industrial_safety'),
('0049','сусыма материалдар','сыпучие материалы','bulk materials, granular materials','industrial_safety'),
('0049','соқтығысып иондалу','ударная ионизация','impact ionization','industrial_safety'),
('0049','санитариялық тексеру актісі','акт санитарного обследования','sanitary inspection report','disaster_medicine'),
('0049','сіреспе анатоксині','анатоксин столбнячный','tetanus toxoid','disaster_medicine'),
('0049','странгуляциялық тұншығу','асфиксия странгуляционная','strangulation asphyxia','disaster_medicine'),
('0049','сан артериясы','артерия бедренная','femoral artery','disaster_medicine'),
('0049','сыртқы ұйқы күретамыры','артерия сонная наружная','external carotid artery','disaster_medicine'),
('0049','синустық аритмия','аритмия синусовая','sinus arrhythmia','disaster_medicine'),
('0049','сөйлей алмау','афазия','aphasia','disaster_medicine'),
('0049','суға ауа сіңіру','аэрация воды','water aeration','industrial_safety'),
('0049','сәуле ауруы','болезнь лучевая','radiation sickness, radiation disease','disaster_medicine'),
('0049','сәулесоқ ауру','болезнь лучевая','radiation sickness, radiation disease','disaster_medicine'),
('0049','синустық брадикардия','брадикардия синусовая','sinus bradycardia','disaster_medicine'),
('0049','сырқат','больной','patient, sick person','disaster_medicine'),
('0049','сұққылап ауыру','боль колющая','stabbing pain, sharp pain','disaster_medicine'),
('0049','су-тұз теңгерімі','водно-солевой баланс','water-electrolyte balance','disaster_medicine'),
('0049','су эпидемиясы','водные эпидемии','waterborne diseases','disaster_medicine'),
('0049','сутартқыш заттек','водоотнимающее вещество','dehydrating agent','industrial_safety'),
('0049','сутектік көрсеткіш','водородный показатель','hydrogen ion exponent (pH)','industrial_safety'),
('0049','сарапшы дәрігер','врач эксперт','medical expert','disaster_medicine'),
('0049','субдуралдық гематома','гематома субдуральная','subdural hematoma','disaster_medicine'),
('0049','сырқаттанушылық','заболеваемость','morbidity','disaster_medicine'),
('0049','сырғытқы','каталка','patient trolley','disaster_medicine'),
('0049','санитариялық киім','санитарная одежда','protective clothing','disaster_medicine'),
('0050','ядролық жарылыс түрлері','виды ядерных взрывов','types of nuclear explosions','civil_defense'),
('0050','ядролық соғыс','война ядерная','nuclear war','civil_defense'),
('0050','ядро заряды','заряд ядра','nuclear charge','civil_defense'),
('0050','ядролық жарылыстарды белгілеу','засечка ядерных взрывов','nuclear detonation detection','civil_defense'),
('0050','ядроның бөлінуі','разделение ядер','nuclear fission','industrial_safety'),
('0050','ядролық жарылыстың соққы толқыны','ударная волна ядерного взрыва','nuclear blast wave','civil_defense'),
('0050','ядролық реакцияның энергетикалық шығымы','энергетический выход ядерной реакции','nuclear energy yield','industrial_safety'),
('0050','ядроның байланыс энергиясы','энергия связи ядра','nuclear binding energy','industrial_safety'),
('0050','ядролық авария','ядерная авария','nuclear accident','emergencies'),
('0050','ядролық қауіпсіздік','ядерная безопасность','nuclear safety','industrial_safety'),
('0050','ядролы бомба','ядерная бомба','nuclear bomb','civil_defense'),
('0050','ядролы мина','ядерная мина','nuclear mine','civil_defense'),
('0050','ядролық реакция','ядерная реакция','nuclear reaction','industrial_safety'),
('0050','ядролық физика','ядерная физика','nuclear physics','industrial_safety'),
('0050','ядролық электроника','ядерная электроника','nuclear electronics','industrial_safety'),
('0050','ядролық энергетика','ядерная энергетика','nuclear power, nuclear energy industry','industrial_safety'),
('0050','ядролық энергетикалық қондырғы','ядерная энергетическая установка','nuclear power plant, nuclear propulsion plant','industrial_safety'),
('0050','ядролық энергия','ядерная энергия','nuclear energy, atomic energy','industrial_safety'),
('0050','ядролы-миналық бөгеттер','ядерно-минные заграждения','nuclear landmines, atomic demolition munitions (ADMs)','civil_defense'),
('0050','ядролық жарылғыш зат','ядерное взрывчатое вещество','nuclear explosive material','civil_defense'),
('0050','ядролық уақыт','ядерное время','nuclear time','coordination'),
('0050','ядролық сәулешығару','ядерное излучение','nuclear radiation','industrial_safety'),
('0050','ядролық қару','ядерное оружие','nuclear weapons','civil_defense'),
('0050','ядролық қарусыздану','ядерное разоружение','nuclear disarmament','civil_defense'),
('0050','ядролық сақтандыру','ядерное страхование','nuclear insurance','coordination'),
('0050','ядролық отын','ядерное топливо','nuclear fuel','industrial_safety'),
('0050','ядролық күштер','ядерные силы','nuclear forces','civil_defense'),
('0050','ядролы оқ-дәрі','ядерный боеприпас','nuclear weapon','civil_defense'),
('0050','ядролық жарылыс','ядерный взрыв','nuclear explosion','civil_defense'),
('0050','ядролық заряд','ядерный заряд','nuclear warhead','civil_defense'),
('0050','ядролық парамагнетизм','ядерный парамагнетизм','nuclear paramagnetism','industrial_safety'),
('0050','ядролық реактор','ядерный реактор','nuclear reactor','industrial_safety'),
('0050','ядро шырыны','ядерный сок','nucleoplasm, nuclear sap','industrial_safety'),
('0050','ядро','ядро','nucleus','industrial_safety'),
('0050','ядрошық','ядрышко','nucleolus','industrial_safety'),
('0050','ярлык','ярлык','label, shortcut, tag','coordination')) as f(src,kk,ru,en,cat)
where not exists (select 1 from public.terms t where lower(t.kk)=lower(f.kk) and lower(t.ru)=lower(f.ru));

insert into public.terms (kk, ru, en, category)
select 'көрсетілім', 'демонстрация', 'demonstration', 'coordination'
where not exists (select 1 from public.terms t where lower(t.kk) = 'көрсетілім' and lower(t.ru) = 'демонстрация');

select (select count(*) from public.terms) as terms_now;

commit;
